login_call_check_username
gradido/gradido pull request #1037
Opened 2021-10-22 00:47 UTC by ulfgebhardt

## 🍰 Pullrequest

Replaces the `checkUsername` call to the `login_server`

### Issues

- requires #1031
- fixes #839 

### Todo

- [X] None

2021-10-30 03:07 UTC, ulfgebhardt commented on backend/src/graphql/resolver/UserResolver.ts
> +    if (username.length < MIN_CHARACTERS_USERNAME) {
There is no additional regex checks for the username in the login server code as far as I can see.
I made a followup ticket: https://github.com/gradido/gradido/issues/1069

2021-11-04 08:33 UTC, Elweyn requested changes

2021-11-04 08:33 UTC, Elweyn commented on backend/src/graphql/resolver/UserResolver.ts
> +    const usersFound = await LoginUser.count({ username })
Needs to be the LoginUserRepository
```suggestion
    const loginUserRepository = getCustomRepository(LoginUserRepository)
    const usersFound = await loginUserRepository.count({ username })
```

2021-11-04 09:26 UTC, Mogge approved these changes

2021-11-04 09:29 UTC, Elweyn approved these changes

2021-11-04 12:53 UTC, merged