Documentation on the coin creation and the steps to have the accounts…
gradido/gradido pull request #1052
Opened 2021-10-27 13:10 UTC by Elweyn

## 🍰 Pullrequest
Documentation of how to have the 2 accounts to create coins.

### Issues
- None

### Todo

- [X] None

2021-10-31 19:58 UTC, einhornimmond approved these changes

2021-11-01 03:51 UTC, ulfgebhardt requested changes

2021-11-01 03:51 UTC, ulfgebhardt commented on docu/create-coins-as-admin.md
> +Pending_tasks table is used to store the transactions which not signed or had errors
```suggestion
Furthermore we must sign the transactions we created. Normally after klick of the left Button (Transaktion abschließen) it should be automatic 
forwarding to http://$community_domain/account/checkTransactions where we can do this.
If not this page can also be reached by clicking on the shield-icon with the hook in it on the Dashboard, which is only shown if at least one transaction is waiting for signing. 

For debug purposes you can check the `pending_tasks` table, which is used to store the transactions which are not signed yet or had errors.
```

2021-11-01 17:02 UTC, ulfgebhardt approved these changes

2021-11-01 20:20 UTC, merged

2021-11-02 11:44 UTC, Elweyn commented
@einhornimmond, 
I though that their was an on going discussion, and that I am the one that needs to merge it since I opened the PR. 
But you close it without waiting for any reaction from me.

2021-11-02 18:44 UTC, einhornimmond commented
Tut mir Leid, das war ein Versehen (._.);