[WIP] 1078 gdd calculate decay tool
gradido/gradido pull request #1080
Opened 2021-11-05 16:44 UTC by ogerly

## 🍰 Pullrequest
gdd calculate decay tool

### Issues
- fixes #1078 
 
![FireShot Capture 791 - Gradido Account - localhost](https://user-images.githubusercontent.com/1324583/140546781-e76b0e72-52ec-41a0-a83e-8da62a60e497.png)

2021-11-05 16:57 UTC, BerndHueckstaedt commented
Good idea with calendar!

2021-11-09 11:03 UTC, Mogge requested changes

2021-11-09 11:03 UTC, Mogge commented on frontend/src/locales/de.json
> +    "send_transaction_error": "Leider konnte die Transaktion nicht ausgTeführt werden!",
Please fix

2021-11-24 01:04 UTC, ulfgebhardt commented
@ogerly Can we close this - as far as I understood its now an external standalone tool?! From my point of view we can deploy it with our services but as external tool not directly in the app?

2021-12-08 15:00 UTC, closed without merging