login_call_updateUserInfos
gradido/gradido pull request #1084
Opened 2021-11-07 05:24 UTC by ulfgebhardt

## 🍰 Pullrequest

This implements the call `updateUserInfos` on Apollo where it was implemented on the `login_server` beforehand.

Remarks:
- setting the `disabled` flag was removed
- `publisherId` is now set on login directly, not in updateUserInfos

### Issues

- fixes #838 

### Todo

- [ ] Transactions for the new settings table
- [ ] Change password

2021-11-11 12:12 UTC, Elweyn requested changes
Please take the branch apollo_jwt_withdrawSessionId

2021-11-11 12:12 UTC, Elweyn commented on backend/src/graphql/resolver/UserResolver.ts
> -      publisherId,
Don't we want to update the publisherId anymore?

2021-11-11 12:12 UTC, Elweyn commented on backend/src/graphql/arg/UpdateUserInfosArgs.ts
> -  publisherId?: number
No publisherId update anymore?

2021-11-11 12:12 UTC, Elweyn commented on backend/src/graphql/resolver/UserResolver.ts
> +      loginUser.save()
I am not sure if it has anything to do with the context of this PR!?
I never know when the above line work and when not so:
```suggestion
      const loginUserRepository = getCustomRepository(LoginUserRepository)
      const loginUser = await loginUserRepository.findOneOrFail({ email: userEntity.email })
      loginUser.publisherId = publisherId
      loginUserRepository.save(loginUser)
```

2021-11-11 12:12 UTC, Elweyn commented on backend/src/graphql/resolver/UserResolver.ts
> +    const loginUser = await LoginUser.findOneOrFail({ email: userEntity.email })
Same reflexion as above never know when LoginUser.findOneOrFail or LoginUser.count works or not so I would suggest:
```suggestion
    const loginUserRepository = getCustomRepository(LoginUserRepository)
    const loginUser = await loginUserRepository.findOneOrFail({ email: userEntity.email })
```

2021-11-16 23:22 UTC, ulfgebhardt commented on backend/src/util/sendEMail.ts
> +}): Promise<boolean> => {
True, but would you be willing to turn a blind eye if we can merge this now - if not i can outsource this change.

2021-11-18 00:24 UTC, Elweyn approved these changes
Seems good for me! Nice work!

2021-11-18 00:48 UTC, merged