Login admin interface
gradido/gradido pull request #1125
Opened 2021-11-19 19:02 UTC by ulfgebhardt

## 🍰 Pullrequest

Implements the login/authenticate mechanism for the new admin interface. Furthermore the wayback is implemented and a convenience mode to disabled auth for development

### Issues

- includes #1116 
- includes #1045 

### Todo

- [ ] Convenience mode
- [ ] `isAdmin` from backend
- [ ] logout
- [ ] back2wallet
- [ ] frontend tests

2021-11-22 14:42 UTC, Mogge requested changes

2021-11-22 14:42 UTC, Mogge commented on frontend/src/components/SidebarPlugin/SideBar.vue
> +        <ul class="navbar-nav ml-3" v-if="this.$store.state.isAdmin">
Please Test this

2021-11-22 15:08 UTC, ulfgebhardt commented on frontend/src/routes/guards.js
> +  // store token on authenticate
It will bring you to `not-found` page

2021-11-23 11:25 UTC, Mogge commented
I fixed the test and also checked that logout is dispatched. But I get the following, when clicking on admin interface
```
message | "Controller class Admin could not be found."
-- | --
url | "/admin/authenticate?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdWJLZXkiOiJlMDlhNzk2NTQ1NTM3NTI2YTZkMTFhZjc0OTg1NDFmZjg2MGJkZTg0MzExZTNkYTU4ZjI5Y2NiZWY4MjUzNzQ5IiwiaWF0IjoxNjM3NjY2NjkyLCJleHAiOjE2Mzc2NjcyOTJ9.mfvCZIcd_ub5BSxprLdC3iPUMXO_pWiKfIYlAipfdic"
code | 404
file | "/var/www/cakephp/vendor/cakephp/cakephp/src/Http/ControllerFactory.php"
line | 105
```
Looks like nginx is not working as expected. On my setup I can access localhost/admin

2021-11-23 11:49 UTC, ulfgebhardt commented on frontend/src/components/SidebarPlugin/SideBar.vue
> +        <ul class="navbar-nav ml-3" v-if="this.$store.state.isAdmin">
🤷🏻

2021-11-24 20:14 UTC, Mogge approved these changes

2021-11-24 20:23 UTC, merged