backend_rights
gradido/gradido pull request #1126
Opened 2021-11-20 18:37 UTC by ulfgebhardt

## 🍰 Pullrequest

Implements a roles & rights based system for authentication & authorization.

### Issues

- based on #1125 

### Todo

- [ ] Admin role check (requires #1121 )
- [ ] Clarify if we want to encode role in jwt to save a constant database query @Mogge 
- [ ] test

2021-11-22 15:12 UTC, Mogge requested changes
This is not going to work like this. we have lots of calls that never will have a token, but by setting `@Authorized(SOME_ROLE)` you must have a token, as it is designed by now.

2021-11-22 15:12 UTC, Mogge commented on backend/src/graphql/resolver/UserResolver.ts
> +  @Authorized([RIGHTS.RESET_PASSWORD])
No token?

2021-11-22 15:12 UTC, Mogge commented on backend/src/graphql/resolver/UserResolver.ts
> +  @Authorized([RIGHTS.CHECK_USERNAME])
No token?

2021-11-22 15:12 UTC, Mogge commented on backend/src/graphql/resolver/UserResolver.ts
> +  @Authorized([RIGHTS.CHECK_EMAIL])
No token

2021-11-22 15:12 UTC, Mogge commented on backend/src/graphql/resolver/UserResolver.ts
> +  @Authorized([RIGHTS.LOGIN])
No token

2021-11-22 15:12 UTC, Mogge commented on backend/src/auth/JWT.ts
> +export const decode = (token: string): CustomJwtPayload | null => {
Stupid question. From the context, of course :)

2021-11-22 15:14 UTC, ulfgebhardt commented on backend/src/auth/JWT.ts
> +export const decode = (token: string): CustomJwtPayload | null => {
The JWT is called token in this context I believe.

2021-11-25 08:59 UTC, ulfgebhardt commented
@Mogge Please have a look at this - especially the `isAuthorized` - we make a database query on every call to the server to figure out the role - alternatively we can save the role identifier or whatever in JWT and prevent an additional query.

2021-11-25 17:25 UTC, Mogge approved these changes

2021-11-25 17:53 UTC, merged