Login call reset password frontend
gradido/gradido pull request #1133
Opened 2021-11-23 08:41 UTC by Elweyn

## 🍰 Pullrequest
The frontend needs to be changed so that we set the password after the registration has been done & the acount is activated.

### Issues

- relates #1130  

### Todo

- [ ] Register form withdraw password fields
- [ ] Refactor ResetPassword so that it works for /reset & /checkEmail
- [ ] Send them to thx/reset or thx/checkEmail

2021-11-24 03:33 UTC, ulfgebhardt commented
@Elweyn Damn I haven't seen this in time - i made a basic implementation of the frontend to test the backend - so no text changes or any fancy hint texts like you did - we should try to combine both PRs as soon as possible in order to not make the work twice.
See: #1130

2021-11-24 07:26 UTC, Mogge requested changes

2021-11-24 07:26 UTC, Mogge commented on backend/src/graphql/resolver/UserResolver.ts
> +    let emailAlreadySend = false
I think we do not need this variable.

2021-11-24 07:26 UTC, Mogge commented on backend/src/graphql/resolver/UserResolver.ts
> +      emailAlreadySend = true
Here the code from line 469 to 474

2021-11-24 07:26 UTC, Mogge commented on backend/src/graphql/resolver/UserResolver.ts
> +    if (emailAlreadySend) {
Move after the if clause

2021-11-24 07:26 UTC, Mogge commented on backend/src/graphql/resolver/UserResolver.ts
> +    const emailSent = await sendEMail({
TO DO: localize the email body and subject

2021-11-24 07:26 UTC, Mogge commented on frontend/src/locales/de.json
> +      "set": "Passwort festsetzen",
May be better `festlegen`

2021-11-24 07:26 UTC, Mogge commented on frontend/src/locales/en.json
> +        "not-authenticated": "Leider konnten wir dich nicht authentifizieren. Bitte wende dich an den Support.",
```suggestion
        "not-authenticated": "Unfortunately we could not authenticate you. Please contact the support.",
```

2021-11-24 07:26 UTC, Mogge commented on frontend/src/locales/en.json
> +      "send_now": "Jetzt senden",
```suggestion
      "send_now": "Send now",
```

2021-11-24 07:26 UTC, Mogge commented on frontend/src/locales/en.json
> +      "set": "Passwort festsetzen",
```suggestion
      "set": "Set password",
```

2021-11-24 07:26 UTC, Mogge commented on frontend/src/locales/en.json
> +        "text": "Jetzt kannst du ein neues Passwort speichern, mit dem du dich zukünftig in der Gradido-App anmelden kannst."
```suggestion
        "text": "Now you can save a new password to login to the Gradido-App in the future."
```

2021-11-24 07:26 UTC, Mogge commented on frontend/src/views/Pages/ResetPassword.vue
>    mounted() {
```suggestion
  async mounted() {
```

2021-11-24 07:26 UTC, Mogge commented on frontend/src/views/Pages/ResetPassword.vue
>      this.authenticate()
```suggestion
    await this.authenticate()
```

2021-11-26 01:51 UTC, ulfgebhardt commented
closing this since its now part of #1130
@Elweyn

2021-11-26 01:51 UTC, closed without merging