onboarding process document
gradido/gradido pull request #1148
Opened 2021-11-30 14:31 UTC by powerzenbob

## 🍰 Pullrequest

### Issues
- relates #1118 

### Todo

- [X] None

2021-11-30 14:36 UTC, Mogge requested changes
Please supply a markdown document

2021-12-01 20:06 UTC, ogerly commented
hier habe ich mal ein beispiel angelegt wie ein project an dem früher mitgearbeitet habe .. anlegt und startet. 
https://github.com/ogerly/hc-install-docker
dabei habe ich quasi eine README.md angelegt .. 

eventuell könnten wir so was für gradido anlegen.

2021-12-22 13:23 UTC, ulfgebhardt approved these changes

2022-01-10 10:52 UTC, Elweyn approved these changes

2022-01-12 21:11 UTC, merged