catch error Client certificate revoked and pass error.session-expired…
gradido/gradido pull request #1152
Opened 2021-12-03 12:14 UTC by ogerly

## 🍰 Pullrequest
catch error Client certificate revoked and pass error.session-expired. Graph QL error: always passed from backend

### Issues
- fixes #1029 
- 
![Bildschirmfoto von 2021-12-03 12-36-23](https://user-images.githubusercontent.com/1324583/144600687-4be24b26-0305-4c99-a26f-3a0bc534fb6e.png)

2021-12-06 08:41 UTC, Mogge requested changes
Das scheint mir keine gute Idee zu sein. Wir fangen in der main global ab, dass die Session nicht abgelaufen ist. Für alle API calls. Warum jetzt nur auf einem. Was ist die Motivation?

2021-12-06 08:44 UTC, ogerly commented
> Das scheint mir keine gute Idee zu sein. Wir fangen in der main global ab, dass die Session nicht abgelaufen ist. Für alle API calls. Warum jetzt nur auf einem. Was ist die Motivation?


https://github.com/gradido/gradido/issues/1029

2021-12-08 14:48 UTC, Mogge approved these changes

2021-12-08 14:51 UTC, ulfgebhardt approved these changes

2021-12-08 14:51 UTC, ulfgebhardt commented on frontend/src/main.js
> +    return payload.replace(/^GraphQL error: /, '')
Dirty hacks....

2021-12-08 14:58 UTC, merged