Error handling in GddTransactionList.vue
gradido/gradido pull request #1183
Opened 2021-12-10 11:27 UTC by ogerly

## 🍰 Pullrequest
in der frontend/src/views/Pages/AccountOverview/GddTransactionList.vue habe ich drei Fehlermeldungen hinzugefügt. 

1. Wenn keine Variable übermittelt wird
**english**: Unfortunately, there was an error. No transactions are being sent from the server.
**german**:  Es gab leider einen Fehler. Es werden keine Transaktionen vom Server übermittelt.
![FireShot Capture 825 - Gradido Account - localhost](https://user-images.githubusercontent.com/1324583/145566819-4b6fbc55-0931-49dd-956c-c004063dae50.png)

2. Wenn Varable lehr ist
**english** :There are no transactions under your account yet.
**german**: Es gibt noch keine Transaktionen unter deinem Account.
 ![FireShot Capture 823 - Gradido Account - localhost](https://user-images.githubusercontent.com/1324583/145566806-f9b3eac8-c56e-4ba4-8f50-06a57ad4a39a.png)

3. Wenn kein Decay berechnet wird, fehlt. 
**english** :Error: No Decay available, please check the code!
**german**: Fehler: Kein Decay vorhanden, bitte prüfe den Code!
![FireShot Capture 826 - Gradido Account - localhost](https://user-images.githubusercontent.com/1324583/145566835-2e32c979-27f8-4c6f-b095-13a4abe99d19.png)

2021-12-13 09:06 UTC, Mogge requested changes

2021-12-13 09:06 UTC, Mogge commented on frontend/src/locales/de.json
> +    "no-transactionlist": "Es gab leider einen Fehler. Es werden keine Transaktionen vom Server übermittelt",
```suggestion
    "no-transactionlist": "Es gab leider einen Fehler. Es wurden keine Transaktionen vom Server übermittelt",
```

2021-12-13 09:06 UTC, Mogge commented on frontend/src/locales/en.json
> +    "no-transactionlist": "Unfortunately, there was an error. No transactions are being sent from the server.",
```suggestion
    "no-transactionlist": "Unfortunately, there was an error. No transactions have been sent from the server.",
```

2021-12-13 09:06 UTC, Mogge commented on frontend/src/views/Pages/AccountOverview/GddTransactionList.spec.js
> +        expect(wrapper.find('div.gdd-transaction-list').text()).toBe(
Besser zwei expect mit `toContain`

2021-12-13 09:06 UTC, Mogge commented on frontend/src/views/Pages/AccountOverview/GddTransactionList.vue
> +      <div v-if="!transactions" class="text-right">
Bitte testen

2021-12-13 09:06 UTC, Mogge commented on frontend/src/views/Pages/AccountOverview/GddTransactionList.vue
> +      <div v-if="!transactionCount" class="text-right">
Bitte testen

2021-12-14 08:59 UTC, ogerly commented on frontend/src/views/Pages/AccountOverview/GddTransactionList.spec.js
> +        expect(wrapper.find('div.gdd-transaction-list').text()).toBe(
habe ich geändert

2021-12-14 09:01 UTC, ogerly commented on frontend/src/views/Pages/AccountOverview/GddTransactionList.vue
> +      <div v-if="!transactionCount" class="text-right">
zwei tests angelegt 
1. test ob array(transaction) === false ist 
2. number(transactionCount) === 0

2021-12-14 09:01 UTC, ogerly commented on frontend/src/views/Pages/AccountOverview/GddTransactionList.vue
> +      <div v-if="!transactions" class="text-right">
getestet

2021-12-14 15:21 UTC, Mogge submitted a review, later dismissed

2021-12-16 08:44 UTC, ogerly commented on frontend/src/views/Pages/AccountOverview/GddTransactionList.spec.js
> +        )
geändert

2021-12-16 10:02 UTC, Elweyn approved these changes

2021-12-16 11:50 UTC, ulfgebhardt approved these changes

2021-12-16 11:52 UTC, merged