language_updates_bernd
gradido/gradido pull request #1260
Opened 2022-01-07 18:23 UTC by ulfgebhardt

## 🍰 Pullrequest

update for the langauge strings I got from Bernd

### Issues

- None

### Todo

- [X] None

2022-01-10 12:37 UTC, Mogge requested changes
Toller PR. Verbessert die Anwendung immens! Ich habe zwei kleine Fehler gefunden.

2022-01-10 12:37 UTC, Mogge commented on frontend/src/locales/de.json
> +      "activateEmail": "Deine Konto wurde noch nicht aktiviert. Bitte überprüfe deine E-Mail und klicke den Aktivierungslink!",
```suggestion
      "activateEmail": "Dein Konto wurde noch nicht aktiviert. Bitte überprüfe deine E-Mail und klicke den Aktivierungslink!",
```

2022-01-11 19:51 UTC, BerndHueckstaedt commented on frontend/src/locales/de.json
> +      "activateEmail": "Deine Konto wurde noch nicht aktiviert. Bitte überprüfe deine E-Mail und klicke den Aktivierungslink!",
Dein Konto

2022-01-11 19:51 UTC, BerndHueckstaedt commented on frontend/src/locales/de.json
> +    "continue-to-registration": "Z",
"Weiter zur Registrierung"

2022-01-12 05:42 UTC, ulfgebhardt commented on frontend/src/locales/de.json
> +    "continue-to-registration": "Z",
```suggestion
    "continue-to-registration": "Weiter zur Registrierung",
```

2022-01-12 05:43 UTC, ulfgebhardt commented
@Mogge Please review - I changed according to your suggestions after Bernds approves

2022-01-12 08:46 UTC, Mogge approved these changes

2022-01-12 09:09 UTC, merged