defined fields for Transactionlist in UserSearch in Adminarea, add Lo…
gradido/gradido pull request #1322
Opened 2022-01-19 13:41 UTC by ogerly

## 🍰 Pullrequest

1.  decay.balance wird sauber angezeigt, wenn kein decay dann 0 
2. Das Datum ist in einem sauberen Format
3.  folgende punkte aus der Transactiontabelle wurden entfernt
Decay Start | Decay End | Decay Duration | E-Mail | Typename
(siehe Bild)

### Issues
- fixes #1320 
 
![FireShot Capture 923 - Gradido Admin Interface - localhost](https://user-images.githubusercontent.com/1324583/150141852-93841719-3702-41a9-9355-1e3ee7d07dda.png)

2022-01-19 16:08 UTC, Mogge requested changes

2022-01-19 16:08 UTC, Mogge commented on admin/src/components/CreationTransactionListFormular.vue
> +            return this.$moment(value).format(this.$t('transactionlist.formatter'))
What about `this.$d(value, 'short')`?

2022-01-19 19:14 UTC, ulfgebhardt approved these changes

2022-01-20 11:23 UTC, Mogge submitted a review, later dismissed

2022-01-20 11:23 UTC, Mogge commented on admin/src/components/CreationTransactionListFormular.vue
> +            return this.$moment(value).format(this.$t('transactionlist.formatter'))
`return this.$d(new Date(value))` geht.

2022-01-20 12:23 UTC, ogerly commented on admin/src/components/CreationTransactionListFormular.vue
> +            return this.$moment(value).format(this.$t('transactionlist.formatter'))
ok ... erledigt

2022-01-20 16:15 UTC, merged