1303 thanks page after set password
gradido/gradido pull request #1335
Opened 2022-01-21 12:50 UTC by ogerly

## 🍰 Pullrequest
Es wird beim request geprüft welche url verwendet wird. und die jeweilige url an thx aufgerufen .. 

### Issues
- fixes #1303 

wenn checkMail passwort eingabe success
![FireShot Capture 933 - Gradido Account - localhost](https://user-images.githubusercontent.com/1324583/150525872-54b98c82-c3cf-423a-a54a-710b600cb2c0.png)

wenn passwort ändern success 
![FireShot Capture 929 - Gradido Account - localhost](https://user-images.githubusercontent.com/1324583/150525843-a265ce9d-954f-4f9d-a49a-eda2d0b41a17.png)

2022-01-21 14:24 UTC, Elweyn requested changes

2022-01-21 14:24 UTC, Elweyn commented on frontend/src/views/Pages/ResetPassword.vue
> +          }
With this code it should check every if block, in my opinion the following would be a bit more efficient: 
```suggestion
          if (this.$route.path.includes('checkEmail')) {
            this.$router.push('/thx/checkEmail')
          } else if (this.$route.path.includes('reset')) {
            this.$router.push('/thx/reset')
          }
```

2022-01-23 08:09 UTC, Elweyn submitted a review, later dismissed

2022-01-23 08:09 UTC, Elweyn commented on frontend/src/views/Pages/ResetPassword.spec.js
>            it('redirects to "/thx/reset"', () => {
```suggestion
          it('redirects to "/thx/checkEmail"', () => {
```

2022-01-24 13:33 UTC, ogerly commented on frontend/src/views/Pages/ResetPassword.spec.js
>            it('redirects to "/thx/reset"', () => {
erledigt

2022-01-24 14:52 UTC, Mogge requested changes

2022-01-24 14:52 UTC, Mogge commented on frontend/src/views/Pages/ResetPassword.spec.js
> +          it('redirects to "/thx/heckEmail"', () => {
```suggestion
          it('redirects to "/thx/checkEmail"', () => {
```

2022-01-24 16:24 UTC, merged