change standard text für cration
gradido/gradido pull request #1343
Opened 2022-01-26 11:11 UTC by ogerly

## 🍰 Pullrequest
text alt
"Creation for January 2022"
"Schöpfung für January 2022"

text new:
engish: Active Basic Income for January 2022
deutsch : Aktives Grundeinkommen für Januar 2022

### Issues
- fixes #1342

2022-01-26 13:38 UTC, Elweyn requested changes

2022-01-26 13:38 UTC, Elweyn commented on admin/src/locales/de.json
> +    "creation_for": "Aktives Grundeinkommen für ",
```suggestion
    "creation_for": "Aktives Grundeinkommen für",
```

2022-01-26 14:21 UTC, Mogge requested changes

2022-01-26 14:21 UTC, Mogge commented on admin/src/locales/de.json
> +    "creation_for": "Aktives Grundeinkommen für ",
Good Catch

2022-01-27 12:22 UTC, Mogge approved these changes

2022-01-27 23:16 UTC, merged