if an email is not confirmed, a user cannot be added to any multiple …
gradido/gradido pull request #1374
Opened 2022-01-29 11:24 UTC by ogerly

## 🍰 Pullrequest
if an email is not confirmed, a user cannot be added to any multiple creation. 
If there is no confirmed email for a user ... then **Email!** is written in the bookmar field.

### Issues
- fixes #1372 

![FireShot Capture 956 - Gradido Admin Interface - localhost](https://user-images.githubusercontent.com/1324583/151658914-60883268-315b-4595-9823-3bd939bc9c42.png)

TODO: https://github.com/gradido/gradido/issues/1373 check on the backend page if the email is confirmed before a creation, if not, no creation may be performed and an error with info will be returned.

2022-01-31 15:56 UTC, Mogge requested changes

2022-01-31 15:56 UTC, Mogge commented on admin/src/components/UserTable.vue
> +          <div v-else>E-Mail!</div>
Please localize.

2022-02-01 09:04 UTC, ogerly commented on admin/src/components/UserTable.vue
> +          <div v-else>E-Mail!</div>
ok

2022-02-01 16:44 UTC, Mogge approved these changes

2022-02-02 11:10 UTC, merged