tutorial decay start block
gradido/gradido pull request #1414
Opened 2022-02-03 08:20 UTC by ogerly

## 🍰 Pullrequest
data from https://github.com/gradido/gradido/pull/1193

 
### Issues
fixes: #1193

2022-02-03 12:16 UTC, Elweyn approved these changes

2022-02-03 12:36 UTC, Mogge requested changes
Das ist vermutlich morgen obsolet. Siehe: https://github.com/gradido/gradido/pull/1405

2022-02-03 13:30 UTC, ogerly commented
> Das ist vermutlich morgen obsolet. Siehe: #1405

ok .. super .. sehr gut :)

2022-02-07 14:47 UTC, ogerly commented
@ulfgebhardt können wir das schließen ?

2022-02-16 11:49 UTC, closed without merging