1216 seo vorschau links
gradido/gradido pull request #1426
Opened 2022-02-05 08:25 UTC by ogerly

## 🍰 Pullrequest

add meta datas

### Issues
- fixes #1216

2022-02-07 11:22 UTC, ulfgebhardt requested changes

2022-02-07 11:22 UTC, ulfgebhardt commented on frontend/public/index.html
> +  <meta name="description" lang="en" content="Gradido Wallet from Gradido-Akademie">
```suggestion
  <meta name="description" lang="en" content="Gradido Wallet of Gradido-Akademie">
```

2022-02-07 11:22 UTC, ulfgebhardt commented on frontend/public/index.html
> +  <meta name="keywords" lang="de" content="Grundeinkommen, aktives, Wallet, tauschen, schenken, Geldsystem, alternativ, Vergänglichkeit">
```suggestion
  <meta name="keywords" lang="de" content="aktives Grundeinkommen, Wallet, tauschen, schenken, Geldsystem, alternativ, Vergänglichkeit, Kreislauf des Lebens, Bionik">
```

2022-02-07 11:22 UTC, ulfgebhardt commented on frontend/public/index.html
> +  <meta name="keywords" lang="en" content="Basic income, active, wallet, exchange, gift, monetary system, alternative, decay">
```suggestion
  <meta name="keywords" lang="en" content="active basic income, wallet, exchange, gift, monetary system, alternative, decay, cycle of life, bionics">
```

2022-02-07 11:22 UTC, ulfgebhardt commented on frontend/public/index.html
> +  <meta name="robots" content="noindex,nofollow">
```suggestion
  <meta name="robots" content="index,follow">
```

2022-02-07 14:29 UTC, Elweyn requested changes
It would be great to have the URL, title and more taken automatically out of the config file.
But we don't need to make it on this PR, but let's make an issue out of it.

2022-02-07 14:29 UTC, Elweyn commented on frontend/public/index.html
> +  <meta name="url" content="http://www.gdd.gradido.net">
```suggestion
  <meta name="url" content="https://gdd.gradido.net">
```

2022-02-07 16:54 UTC, Mogge requested changes
Es ist wichtig, das @BerndHueckstaedt sich das anschaut.

2022-02-07 16:54 UTC, Mogge commented on frontend/public/index.html
> +  <meta name="description" lang="de" content="Gradido Wallet der Gradido-Akademie">
@BerndHueckstaedt Das klingt sehr holprig. Hast du eine bessere Idee?

2022-02-07 16:54 UTC, Mogge commented on frontend/public/index.html
> +  <meta name="keywords" lang="en" content="active basic income, wallet, exchange, gift, monetary system, alternative, decay, cycle of life, bionics">
Keyword correct?

2022-02-09 11:58 UTC, BerndHueckstaedt commented
Gradido – Dein Dankbarkeitskonto
Gradido - Your gratitude account

Dankbarkeit ist die Währung der neuen Zeit. Immer mehr Menschen entfalten ihr Potenzial und gestalten eine gute Zukunft für alle.

Gratitude is the currency of the new age. More and more people are unleashing their potential and shaping a good future for all.

Keywords:
Grundeinkommen, Währung, Dankbarkeit, Schenk-Ökonomie, Natürliche Ökonomie des Lebens, Ökonomie, Ökologie, Potenzialentfaltung, Schenken und Danken, Kreislauf des Lebens, Geldsystem

Basic Income, Currency, Gratitude, Gift Economy, Natural Economy of Life, Economy, Ecology, Potential Development, Giving and Thanking, Cycle of Life, Monetary System

2022-02-09 14:04 UTC, Mogge submitted a review, later dismissed
Ich habe die Vorschläge von @BerndHueckstaedt  eingearbeitet. Ich bin mir nicht sicher was wir mit den `og` properties machen sollen.

2022-02-09 14:04 UTC, Mogge commented on frontend/public/index.html
> +  <meta name="twitter:title" content="Gradido Akademie">
```suggestion
  <meta lang="de" name="twitter:title" content="Gradido – Dein Dankbarkeitskonto">
  <meta lang="en" name="twitter:title" content="Gradido - Your gratitude account">
```

2022-02-16 14:44 UTC, ogerly commented
@Mogge  die og: documentation https://ogp.me/

2022-02-16 16:16 UTC, ulfgebhardt commented on frontend/public/index.html
> +* Gradido Konto - v1.6.1
todo @ulfgebhardt

2022-03-10 23:13 UTC, ulfgebhardt approved these changes
lets merge this

2022-03-11 12:12 UTC, merged