1106 first transaction cannot be expanded
gradido/gradido pull request #1432
Opened 2022-02-07 11:25 UTC by Elweyn

## 🍰 Pullrequest
First transaction has a expand button and has a text that their is no decay.

### Issues
- fixes #1106 

### Todo

2022-02-07 11:36 UTC, ulfgebhardt requested changes
![image](https://user-images.githubusercontent.com/1238238/152781032-c1e5b2e5-dc8e-4114-a518-37430538bb97.png)

![image](https://user-images.githubusercontent.com/1238238/152780848-67deeb33-2e8f-46e5-b5c4-6521cea5dfa4.png)

The first block is now expandable, but the other ones are not if they are before the decay start block.

2022-02-07 11:37 UTC, ulfgebhardt commented
@Mogge We need seed data for this case

2022-02-07 16:48 UTC, Mogge submitted a review, later dismissed

2022-02-07 16:48 UTC, Mogge commented on frontend/src/locales/de.json
> +    "first_transaction": "Die erste Transanktion binhaltet keinen Vergänglichkeit.",
```suggestion
    "first_transaction": "Die erste Transaktion hat keine Vergänglichkeit.",
```

2022-02-07 16:48 UTC, Mogge commented on frontend/src/locales/en.json
> +    "first_transaction": "The first transanction does not include decay.",
```suggestion
    "first_transaction": "The first transaction  has no decay.",
```

2022-02-07 16:48 UTC, Mogge commented on frontend/src/views/Pages/AccountOverview/GddTransactionList.vue
> +            v-if="(type != 'decay' && decay) || firstTransaction"
```suggestion
            v-if="(type !== 'decay' && decay) || firstTransaction"
```

2022-02-07 16:48 UTC, Mogge commented on frontend/src/views/Pages/AccountOverview/GddTransactionList.vue
> +            v-if="(type != 'decay' && decay) || firstTransaction"
```suggestion
            v-if="(type !== 'decay' && decay) || firstTransaction"
```
It is two times the same code. Can we improve this?

2022-02-07 16:50 UTC, Mogge commented
@ulfgebhardt "@Mogge We need seed data for this case"
I think we cover this case with the seeded creations. These are all first transactions, so the message introduced in this PR must be visible.

2022-02-08 14:00 UTC, ulfgebhardt commented
> @ulfgebhardt "@Mogge We need seed data for this case" I think we cover this case with the seeded creations. These are all first transactions, so the message introduced in this PR must be visible.

No we need seeded data for this

2022-02-08 14:35 UTC, ulfgebhardt reviewed
No button on decay-since-last transaction button, but expendable

![image](https://user-images.githubusercontent.com/1238238/153008491-7905022e-4dd8-4d0e-9105-c6ba834606ff.png)

2022-02-10 20:29 UTC, ogerly commented
![FireShot Capture 990 - Gradido Account - localhost](https://user-images.githubusercontent.com/1324583/153491262-67147509-576f-457f-95f2-b2ec8f705eb6.png)

2022-02-11 14:46 UTC, Mogge commented on frontend/src/components/DecayInformation.vue
> +      <b-row v-if="decaytyp === 'new' || decaytyp === 'decayLastTransaction'">
```suggestion
      <b-row>
```

2022-02-11 14:46 UTC, Mogge commented on frontend/src/components/DecayInformation.vue
> +      <b-row v-if="decaytyp === 'new' || decaytyp === 'decayLastTransaction'">
```suggestion
      <b-row>
```

2022-02-11 14:46 UTC, Mogge commented on frontend/src/components/DecayInformation.vue
> +      <b-row v-if="decaytyp === 'new' || decaytyp === 'decayLastTransaction'">
```suggestion
      <b-row>
```

2022-02-11 14:46 UTC, Mogge commented on frontend/src/components/DecayInformation.vue
> +      <b-row v-if="decaytyp === 'new'">
can we have one block for this case?
```
<div v-if="decaytyp === 'new'">
  <b-row>
  ...
```

2022-02-11 14:46 UTC, Mogge commented on frontend/src/components/Transaction.vue
> +  mounted() {
This could be a mixin. We use the same code in two components

2022-02-11 14:46 UTC, Mogge commented on frontend/src/views/Pages/AccountOverview/GddTransactionList.vue
> +  mounted() {
mixin

2022-02-28 10:33 UTC, ulfgebhardt approved these changes

2022-02-28 10:40 UTC, merged

2022-02-28 10:42 UTC, Elweyn commented
@Mogge you wished changes (mixin) will be done on a new branch basing on #1539