enforce_no_element_style
gradido/gradido pull request #1444
Opened 2022-02-09 10:34 UTC by ulfgebhardt

## 🍰 Pullrequest

Enforce style not to be defined on the element but external at least in a `<style>` tag

### Issues

- None

### Todo

- [X] None

2022-02-09 11:34 UTC, Mogge requested changes
Very quick and dirty :(

2022-02-09 11:34 UTC, Mogge commented on admin/src/pages/UserSearch.vue
> +    <div id="user-search-style-1">
serious?

2022-02-09 11:34 UTC, Mogge commented on frontend/src/views/Pages/AccountOverview/GddTransactionList.vue
> +#collaps-button-style {
```suggestion
.collaps-button-style {
```

2022-02-09 11:34 UTC, Mogge commented on frontend/src/views/Pages/AccountOverview/GddTransactionList.vue
> +#collapse-div-style-1 {
```suggestion
.collapse-div-style-1 {
```

2022-02-10 20:41 UTC, ulfgebhardt commented
> Very quick and dirty :(

I think its adequate - it was you who said we do not invest into style, since we get a new design in the near future anyways. It is expected that all of those style- and the html tags will change completely. I believe its important to have this check in place before we do the design implementation.

2022-03-09 20:22 UTC, closed without merging