Test softdeleted
gradido/gradido pull request #1520
Opened 2022-02-18 11:24 UTC by ogerly

## 🍰 Pullrequest
ich habe PR 1516 und PR 1518 zusammen gelegt.

   - admin/src/components/DeletedUserFormular.vue
   - admin/src/graphql/searchUsers.js
   - backend/src/graphql/model/UserAdmin.ts
   - backend/src/graphql/resolver/AdminResolver.ts

### Issues
- merge #1516  
- merge #1518 

![FireShot Capture 1000 - Gradido Admin Interface - localhost](https://user-images.githubusercontent.com/1324583/154673689-9b04d8f5-52c4-4056-8cf9-e7b10eab720f.png)

2022-02-22 10:27 UTC, ogerly commented
https://user-images.githubusercontent.com/1324583/155113558-c1f40a20-bff4-489b-a923-7545a6ce4cfa.mp4

2022-02-23 08:06 UTC, Mogge requested changes
Vorschläge zur Verbesserung (auch gerne als Folgetickets):
 * [x] Mauszeiger pointer über der ganzen row, click auf row öffnet Details
 * [ ] Refactor Status Icons
 * [x] Refactor toggleRowDetails (wir haben nur noch ein Detail Block und brauchen daher den komplexen Mechanismus nicht mehr).

2022-02-23 08:06 UTC, Mogge commented on database/entity/0016-transaction_signatures/Transaction.ts
> +  userId(userId: any) {
What is this @ulfgebhardt ? What has this to do with the PR?

2022-02-23 08:24 UTC, ogerly commented on admin/src/pages/UserSearch.spec.js
> +jest.spyOn(window, 'alert').mockImplementation(() => {})
als noch eine alert im code war. den es nicht mehr gibt.

2022-02-23 08:30 UTC, ogerly commented on admin/src/components/Tables/SearchUserTable.vue
> +        </div>
icon list wird im grunde nicht mehr angezeigt. 
nur noch 
- email nicht bestätigt (icon: email)
- elopage nicht angemeldet: (icon: elopage)
- gelöschter user (icon: durchgestrichener nutzer)
weitere icons gibt es mometan nicht.

2022-02-23 08:31 UTC, ogerly commented on admin/src/components/Tables/SearchUserTable.vue
> +        <div v-html="data.value" @click="rowToogleDetails(row, 0)"></div>
wir hatten vier varianten. welche ich zu einer gemacht habe. jetzt sehe ich auch das dies einfacher und ohne parameter gehen kann.

2022-02-23 12:29 UTC, ulfgebhardt commented on database/entity/0016-transaction_signatures/Transaction.ts
> +  sendSenderFinalBalance: bigint
???

2022-02-23 17:10 UTC, Mogge approved these changes

2022-02-23 18:29 UTC, ulfgebhardt commented
Can you please make the corresponding tickets you suggested @Mogge ?

2022-02-23 20:16 UTC, merged