90 show release version in frontend
gradido/gradido pull request #153
Opened 2021-04-08 09:02 UTC by ogerly

## 🍰 Pullrequest1
aktuelle Version der app wird im Footer angezeigt

![FireShot Capture 242 - Gradido Account - localhost](https://user-images.githubusercontent.com/1324583/113998949-d7810400-9859-11eb-9367-d07275f8326e.png)

### Issues
- fixes #90

2021-04-08 13:25 UTC, ulfgebhardt requested changes

2021-04-08 13:25 UTC, ulfgebhardt commented on frontend/.env.dist
> +VUE_APP_VERSION=0
```suggestion
```

2021-04-08 13:25 UTC, ulfgebhardt commented on frontend/src/config/index.js
> +  APP_VERSION: process.env.VUE_APP_VERSION || require('./package.json').version,
```suggestion
  APP_VERSION: process.env.APP_VERSION || require('./package.json').version,
```

2021-04-09 09:03 UTC, ogerly reviewed
ich habe neu gepullt

2021-04-09 12:28 UTC, ulfgebhardt approved these changes

2021-04-09 12:36 UTC, merged