Backport balance recalculation
gradido/gradido pull request #155
Opened 2021-04-08 11:53 UTC by einhornimmond

## 🍰 Pullrequest
Way for recalculate balance to compensate calculating errors from previous version

2021-04-08 12:00 UTC, ulfgebhardt requested changes

2021-04-08 12:00 UTC, ulfgebhardt commented on community_server/src/Model/Transactions/TransactionBase.php
> +    }
Line endings seem incorrect (?)

2021-04-08 13:21 UTC, ulfgebhardt approved these changes

2021-04-16 10:28 UTC, ulfgebhardt commented
Since stage2 is now merged do we still need this @einhornimmond ?

2021-04-16 16:47 UTC, einhornimmond commented
no

2021-04-16 16:47 UTC, closed without merging