feat: Add Coverage Check To GitHub Workflow
gradido/gradido pull request #158
Opened 2021-04-08 13:30 UTC by Mogge

## 🍰 Pullrequest
dito

### Issues
- relates #122

2021-04-12 23:25 UTC, Mogge commented
Where is the review?

2021-04-12 23:37 UTC, ulfgebhardt requested changes

2021-04-12 23:37 UTC, ulfgebhardt commented on .github/workflows/test.yml
> +          path-to-lcov: /coverage/lcov.info
Can we please split this in its own job? So its distinguishable from the unit tests?

2021-04-12 23:38 UTC, ulfgebhardt commented on .github/workflows/test.yml
> +          path-to-lcov: /coverage/lcov.info
![image](https://user-images.githubusercontent.com/1238238/114475656-f506f280-9bf8-11eb-9b4c-a63bfe6e0062.png)

Also why PR & push?

Where is the coverage report?

2021-04-13 21:38 UTC, ulfgebhardt approved these changes

2021-04-13 21:42 UTC, merged