refactor: Set Email Optin Valid Time to 24 hours
gradido/gradido pull request #1662
Opened 2022-03-23 15:18 UTC by Mogge

## 🍰 Pullrequest
Sets the valid time for an email optin code to 24h.

### Issues
- relates #1566

### Todo

- [X] None

2022-03-23 15:21 UTC, Mogge commented on frontend/src/pages/ResetPassword.vue
> +          if (
This is terrible code. Furthermore, the previous code did not match any message sent by the server. :(

2022-03-23 19:47 UTC, ulfgebhardt requested changes
we need to separate code valid time from code-request time

2022-03-23 19:47 UTC, ulfgebhardt commented on backend/src/graphql/resolver/UserResolver.ts
> +      throw new Error(`email already sent less than $(printEmailCodeValidTime()} minutes ago`)
this must be a different parameter, which still is 10mins, since if the user loses his code he can not request another for 24h with this code

2022-03-23 19:47 UTC, ulfgebhardt commented on backend/src/graphql/resolver/UserResolver.ts
> +      throw new Error(`email already sent less than ${printEmailCodeValidTime()} ago`)
this must be a different parameter, which still is 10mins, since if the user loses his code he can not request another for 24h with this code

2022-03-23 19:47 UTC, ulfgebhardt commented on backend/src/graphql/resolver/UserResolver.ts
> +      throw new Error(`email was sent more than ${printEmailCodeValidTime()} ago`)
this is ok

2022-03-23 19:47 UTC, ulfgebhardt commented on backend/src/graphql/resolver/UserResolver.ts
> +      throw new Error(`email was sent more than $(printEmailCodeValidTime()} ago`)
this is ok

2022-03-24 18:58 UTC, ulfgebhardt commented on backend/src/graphql/resolver/UserResolver.ts
> +    optInCode.emailOptInTypeId = OptInType.EMAIL_OPT_IN_RESET_PASSWORD
this should be an optional parameter of lin 398  `checkExistingOptInCode(optInCode, user.id, OptInType.EMAIL_OPT_IN_RESET_PASSWORD)`

2022-03-24 18:58 UTC, ulfgebhardt commented on backend/src/graphql/resolver/UserResolver.ts
> +      // why do we delete the code?
yes why?

2022-03-24 18:58 UTC, ulfgebhardt commented on backend/src/graphql/resolver/AdminResolver.ts
> +
dangerous

2022-03-24 18:58 UTC, ulfgebhardt commented on backend/src/graphql/resolver/UserResolver.ts
> +      // why do we delete the code?
In the login server this seems to be implemented differently - the old data contains multiple codes for each user

2022-03-29 09:54 UTC, ulfgebhardt approved these changes

2022-03-29 09:54 UTC, ulfgebhardt commented on backend/src/graphql/resolver/UserResolver.ts
> +  return CONFIG.EMAIL_LINK_SETPASSWORD.replace(/{optin}/g, optInCode.verificationCode.toString())
am I missing something or do we need the redeem code here aswell?

2022-03-29 17:49 UTC, ulfgebhardt approved these changes

2022-03-29 17:49 UTC, merged