feat: Show Link Duration in Emails
gradido/gradido pull request #1663
Opened 2022-03-23 15:59 UTC by Mogge

## 🍰 Pullrequest
Adds text how long the link is valid. Adds a link to forgot password.

### Issues
- relates #1566

### Todo

- [X] None

2022-03-25 08:44 UTC, Elweyn submitted a review, later dismissed

2022-03-25 11:07 UTC, ulfgebhardt requested changes
Blocking merge since we need a rebase on the fixed branch https://github.com/gradido/gradido/pull/1662

2022-03-29 17:54 UTC, ulfgebhardt commented on backend/.env.dist
>  EMAIL_SMTP_PORT=587
new config version

2022-03-29 17:58 UTC, ulfgebhardt approved these changes

2022-03-29 18:25 UTC, ulfgebhardt approved these changes

2022-03-29 18:30 UTC, merged