if no recipientEmail else form.email
gradido/gradido pull request #1722
Opened 2022-04-03 07:54 UTC by ogerly

## 🍰 Pullrequest
After unsuccessful sending email is cleared
if no recipientEmail else form.email

### Issues
- fixes #1706

2022-04-04 11:08 UTC, ulfgebhardt submitted a review, later dismissed

2022-04-04 11:14 UTC, Mogge reviewed
Da gibt es einen auskommentierten Test bzgl. der Email. Geht der mit dieser Änderung?

2022-04-04 11:15 UTC, Mogge requested changes
Siehe oben

2022-04-05 11:01 UTC, Mogge approved these changes

2022-04-05 11:12 UTC, merged