[WIP] add tab system from bootstrap
gradido/gradido pull request #1744
Opened 2022-04-06 08:44 UTC by ogerly

## 🍰 Pullrequest

### Issues
- fixes #1668

2022-04-08 11:42 UTC, ulfgebhardt commented on admin/src/components/Tables/SearchUserTable.vue
> +            <b-tab title="Creations" active :disabled="row.item.deletedAt">
what happens if you open this and the user is deleted?

2022-04-10 13:33 UTC, ogerly commented
if an account is deleted then these tabs are set to disabled

2022-04-12 16:58 UTC, Mogge requested changes

2022-04-12 16:58 UTC, Mogge commented on admin/src/components/Tables/SearchUserTable.vue
> +            <b-tab title="Creations" active :disabled="row.item.deletedAt !== null">
Please localize the title

2022-04-12 16:58 UTC, Mogge commented on admin/src/components/Tables/SearchUserTable.vue
> +              <transaction-link-list :userId="row.item.userId" />
Use the v-if here as well. If not, the Links are queried for a deleted user

2022-04-14 10:41 UTC, ogerly commented
@Mogge  locales all tabs
![FireShot Capture 1113 - Gradido Admin Interface - localhost](https://user-images.githubusercontent.com/1324583/163372167-c9952478-5f0a-46e7-a543-a2f0314a244d.png)

2022-04-14 12:05 UTC, Mogge approved these changes

2022-04-18 12:51 UTC, ulfgebhardt commented on admin/src/components/Tables/SearchUserTable.vue
> +                v-if="!row.item.deletedAt"
do we still need this?

2022-04-18 12:51 UTC, ulfgebhardt commented on admin/src/components/Tables/SearchUserTable.vue
> +              <div v-else>{{ $t('userIsDeleted') }}</div>
do we still need this?

2022-04-18 12:51 UTC, ulfgebhardt commented on admin/src/components/Tables/SearchUserTable.vue
> +                v-if="!row.item.deletedAt"
do we still need this?

2022-04-18 12:51 UTC, ulfgebhardt commented on admin/src/components/Tables/SearchUserTable.vue
> +              <creation-transaction-list v-if="!row.item.deletedAt" :userId="row.item.userId" />
do we still need this `if`?

2022-04-18 12:51 UTC, ulfgebhardt commented on admin/src/components/Tables/SearchUserTable.vue
> +              :title="$t('transactionlink.form_header')"
this locale seems to be off. Use a self-describing string please.

2022-04-18 12:51 UTC, ulfgebhardt commented on admin/src/components/Tables/SearchUserTable.vue
> +              <transaction-link-list v-if="!row.item.deletedAt" :userId="row.item.userId" />
do we still need this `if`?

2022-04-19 07:15 UTC, Mogge commented on admin/src/components/Tables/SearchUserTable.vue
> +              <creation-transaction-list v-if="!row.item.deletedAt" :userId="row.item.userId" />
Yes

2022-04-19 07:16 UTC, Mogge commented on admin/src/components/Tables/SearchUserTable.vue
> +              <transaction-link-list v-if="!row.item.deletedAt" :userId="row.item.userId" />
Yes

2022-04-19 07:16 UTC, Mogge commented on admin/src/components/Tables/SearchUserTable.vue
> +                v-if="!row.item.deletedAt"
Yes

2022-04-19 07:17 UTC, Mogge commented on admin/src/components/Tables/SearchUserTable.vue
> +                v-if="!row.item.deletedAt"
Yes

2022-04-19 12:45 UTC, ulfgebhardt approved these changes

2022-04-19 12:46 UTC, merged