1751 make gtt visible only if explicitly clicked
gradido/gradido pull request #1752
Opened 2022-04-10 08:36 UTC by ogerly

## 🍰 Pullrequest
show GDT balance only by click of tab

### Issues
- fixes #1751 
 

https://user-images.githubusercontent.com/1324583/162609892-cc23fbe7-a356-4945-b2d7-0e51917453b2.mp4

2022-04-11 12:39 UTC, Mogge requested changes
Gut wäre es, wenn der API call auf die GDT transaction list nur auf den Click abgerufen wird.

2022-04-11 12:39 UTC, Mogge commented on frontend/src/pages/Transactions.vue
> +      titel_gdt: this.$t('gdt.gdt'),
```suggestion
      titelGdt: this.$t('gdt.gdt'),
```

2022-04-11 12:39 UTC, Mogge commented on frontend/src/pages/Transactions.vue
> +    showGdtBalance(Boolean) {
```suggestion
    showGdtBalance(boolean) {
```

2022-04-11 12:39 UTC, Mogge commented on frontend/src/pages/Transactions.vue
> +      titel_gdt: this.$t('gdt.gdt'),
Please always camel case for variables.

2022-04-11 12:39 UTC, Mogge commented on frontend/src/pages/Transactions.vue
> +    showGdtBalance(Boolean) {
No capital letter for variables. This looks like a class and not like a variable

2022-04-11 15:51 UTC, ogerly commented on frontend/src/pages/Transactions.vue
> +      titel_gdt: this.$t('gdt.gdt'),
ok

2022-04-12 13:04 UTC, ulfgebhardt requested changes
Please test if the GDT Value appears and disappears correctly

Also please make a followup ticket for communicating the GDT Sum properly to the user (e.g. with a block in the GDT List showing the total)

2022-04-12 14:16 UTC, ogerly commented
Ich hab die funktion entfernt und von dem Tab entfernt und die Summe der GDT über der auflistung angezeigt
![FireShot Capture 1102 -  - localhost](https://user-images.githubusercontent.com/1324583/162982623-2a66499f-b297-40be-b2e3-e8b836e0f0ae.png)

2022-04-19 13:13 UTC, ulfgebhardt approved these changes

2022-04-19 13:31 UTC, merged