1755 insert additional set when redeeming
gradido/gradido pull request #1756
Opened 2022-04-10 10:26 UTC by ogerly

## 🍰 Pullrequest
new locales   "gdd_per_link.isFree": "Gradido is free of charge worldwide.",

### Issues
- fixes #1755 
- 
![FireShot Capture 1095 -  - localhost](https://user-images.githubusercontent.com/1324583/162613835-e974f5f8-d55f-401b-9d6b-dbab8d897052.png)

2022-04-11 12:41 UTC, Mogge approved these changes

2022-04-13 09:55 UTC, Tirokk commented
Shouldn't this lines have the same line ending as in german?

- https://github.com/gradido/gradido/blob/979a48e4389c1e84bb7a745f78cf62f7acf77134/frontend/src/locales/en.json#L36
- https://github.com/gradido/gradido/blob/979a48e4389c1e84bb7a745f78cf62f7acf77134/frontend/src/locales/en.json#L123

2022-04-13 09:57 UTC, Tirokk requested changes
Hey, very nice @ogerly 💫

Looks god in general.


Shouldn't this lines have the same line ending as in german?

- https://github.com/gradido/gradido/blob/979a48e4389c1e84bb7a745f78cf62f7acf77134/frontend/src/locales/en.json#L114
- https://github.com/gradido/gradido/blob/979a48e4389c1e84bb7a745f78cf62f7acf77134/frontend/src/locales/en.json#L123

2022-04-14 07:53 UTC, Tirokk approved these changes
Yeah, I approve 💫

2022-04-14 08:16 UTC, merged