1906 [WIP] feature concept for gdd creation per linkqr code
gradido/gradido pull request #1907
Opened 2022-05-18 00:32 UTC by clauspeterhuebner

## 🍰 Pullrequest

### Issues

- None

### Todo

- [X] None

2022-05-19 12:39 UTC, Mogge requested changes

2022-05-19 12:39 UTC, Mogge commented on .gitignore
> +.dbeaver
```suggestion
```

2022-05-19 12:39 UTC, Mogge commented on .gitignore
> +>>>>>>> refs/remotes/origin/improve-apollo-logging
```suggestion
```

2022-05-25 09:20 UTC, ogerly approved these changes
Auf der einen Seite verstehe ich das als Konzept dies auch in die Zukunft gedacht und gezeichnet werden kann und muss.
Auf der anderen Seite müsste auch noch etwas die Etappen ziele erkennbar werden.
In diesem Umfang wie jetzt das Konzept es darstellt ist, ist es unmöglich dies in einer überschaubaren Zeit zu realisieren.

2022-06-07 14:52 UTC, ogerly submitted a review, later dismissed

2022-06-15 11:00 UTC, clauspeterhuebner commented on .dbeaver/.credentials-config.json.bak
> +��l�"a�`�ù��&�YOl�>u�A�W��TL`���4)4��$;���?'���RX+�!a�"�X[���(0"�l�	hq[�؂�,C��)
*.bak in .gitignore gesetzt

2022-06-15 11:00 UTC, clauspeterhuebner commented on .dbeaver/.data-sources.json.bak
> +}
*.bak in .gitignore gesetzt

2022-06-15 11:02 UTC, clauspeterhuebner commented on .dbeaver/credentials-config.json
> +�_��?��e��B�K�~9!&Rf)v����`�}^<��	&�a�-��w4�c1I�rԙ�d��ONX�[�Bf�Z�X��H�AOy�[c
we discussed about the tool dbeaver

2022-06-15 13:25 UTC, clauspeterhuebner commented on .gitignore
> +.dbeaver/*
darüber haben wir ja gesprochen

2022-06-15 20:48 UTC, ogerly approved these changes

2022-06-15 20:48 UTC, ogerly commented on .gitignore
> +>>>>>>> refs/remotes/origin/master
conflict?

2022-06-15 23:10 UTC, clauspeterhuebner commented on .gitignore
> +>>>>>>> refs/remotes/origin/master
solved

2022-06-21 09:32 UTC, Mogge approved these changes

2022-06-21 22:56 UTC, merged