1929 styling new template for password component
gradido/gradido pull request #1935
Opened 2022-05-25 07:06 UTC by ogerly

## 🍰 Pullrequest

- The ResetPassword page is displayed graphically clean. 
- removed back link because we no longer need this because the component is integrated. 
- remove mobile start page when only checkEmail is retrieved and clicked per link in the registration process. 
__

- Die Seite ResetPassword wird grafisch sauber dargestellt. 
- zurück link wurde entfernt weil wir dies nicht mehr benötigen, weil die Komponente eingebunden wird. 
- remove mobile Startseite wenn nur checkEmail abgerufen wird und per link im Registrierungsprozess geklickt wird. 

### Issues
- fixes #1929 

![FireShot Capture 1204 -  - localhost](https://user-images.githubusercontent.com/1324583/170200397-f6cea0aa-56af-4d83-89e0-133417aa89ed.png)

![FireShot Capture 1203 -  - localhost](https://user-images.githubusercontent.com/1324583/170200405-62b500c8-9472-4e7b-831d-ca248a1a6d94.png)

2022-05-25 08:33 UTC, Tirokk requested changes
Cool! 😍

2022-05-25 08:35 UTC, Tirokk commented on frontend/src/components/Auth/MobileStart.vue
> +    mobileStart: { type: Boolean, default: false },
@ogerly created an issue about this. #1936

2022-05-25 08:35 UTC, Tirokk commented on frontend/src/pages/ResetPassword.vue
> +    this.$emit('is-mobile-start', false)
done

2022-05-25 09:30 UTC, Tirokk submitted a review, later dismissed
That works fine! 🚀💫

2022-05-25 11:02 UTC, ogerly commented
![FireShot Capture 1207 -  - localhost](https://user-images.githubusercontent.com/1324583/170247736-9388ab33-124e-4994-aba2-8eed5ef09c33.png)

2022-05-25 11:05 UTC, Tirokk approved these changes
And I like to give a second approve 😍💫

2022-05-30 05:42 UTC, Mogge approved these changes

2022-05-30 06:22 UTC, merged