[WIP] add list, show, edit, delete and add form for new contribution
gradido/gradido pull request #1950
Opened 2022-05-30 13:41 UTC by ogerly

## 🍰 Pullrequest
- anlegen einer liste für automatische contribution mit den buttons für show, edit und delete einer automatischen contribution
- anlegen eines formulars für neue contributions (name, text, betrag, startDatum. EndDatum)

### Issues
- fixes #1923 
 
 
![Bildschirmfoto vom 2022-05-30 15-36-15](https://user-images.githubusercontent.com/1324583/171004033-524e3d86-a3d2-40f0-a4c7-ba1291110826.png)

![Bildschirmfoto vom 2022-05-30 15-36-38](https://user-images.githubusercontent.com/1324583/171004054-94acb312-27f9-4d94-93b7-48f2ac261186.png)

2022-06-08 11:05 UTC, Tirokk requested changes
Cool thing 🙏🏼🌟

The tests I do review closer when you have brought that to an end.

### Problems

If I edit the first entry:

- de: `Zyclus` is speld correctly `Zyklus` in german
- the `Zyclus` selection has no option selected, see image:

<img width="1341" alt="Bildschirmfoto 2022-06-08 um 11 12 29" src="https://user-images.githubusercontent.com/25344101/172580010-a8754e45-993a-4469-b9ea-565c913d744e.png">

### Suggestions

- Add a copy button to the link modal.

2022-06-08 13:08 UTC, Tirokk commented on admin/src/locales/en.json
> +        "null": "Please select a repetition"
Came in my mind now:

```suggestion
        "null": "please select a repetition"
```

2022-06-08 13:08 UTC, Tirokk commented on admin/src/locales/en.json
> +        "null": "Please select a cycle",
Came in my mind now:

```suggestion
        "null": "please select a cycle",
```

2022-06-08 13:15 UTC, ogerly commented on admin/src/locales/de.json
> +    "noContributionLinks": "Es sind keine Contribution Links angelegt.",
changed in "**Beitragslink**"

2022-06-08 13:17 UTC, ogerly commented on admin/src/locales/de.json
> +  "selectOptions": {},
remove unused selectOptions

2022-06-08 13:18 UTC, ogerly commented on admin/src/locales/en.json
> +        "null": "Please select a cycle",
changed

2022-06-08 13:18 UTC, ogerly commented on admin/src/locales/en.json
> +        "null": "Please select a repetition"
changed

2022-06-08 14:54 UTC, ogerly commented on admin/src/components/ContributionLinkForm.vue
> +        { value: null, text: 'Please select an repetition' },
changed

2022-06-08 19:10 UTC, ogerly commented on admin/src/components/ContributionLinkForm.spec.js
> +    })
changed

2022-06-08 19:14 UTC, ogerly commented on admin/src/components/FigureQrCode.spec.js
> +      expect(wrapper.find('q-r-canvas'))
expect(wrapper.find('.canvas').exists()).toBe(true)

2022-06-15 08:21 UTC, ogerly commented
dies ist teil von https://github.com/gradido/gradido/pull/1981 geworden

2022-06-16 12:15 UTC, ogerly commented
is merged in master

2022-06-16 12:15 UTC, closed without merging