[WIP] 1973 list open contribution links in the wallet
gradido/gradido pull request #1975
Opened 2022-06-08 20:41 UTC by ogerly

## 🍰 Pullrequest
Übersicht für eine Gemeinschaft
- Name
- Beschreibung
- offene Beitraglinksliste
- Moderatorenliste
- Mitgliederzahl

### Issues
 - fixes #1973  

![FireShot Capture 1217 -  - localhost](https://user-images.githubusercontent.com/1324583/172712735-e6edf160-dbca-4f5a-ace2-547514ff9d13.png)

2022-08-05 10:03 UTC, ogerly commented
@Mogge @Elweyn We could put the statistics from moriz on this page. 
I also need a query that lists the moderators (admins) and the number of members.

2022-08-06 09:10 UTC, ogerly commented
i have bookmarked #2041 and have the data displayed. it would be good if this could be seen by all members.

2022-08-18 06:12 UTC, ogerly commented
![image](https://user-images.githubusercontent.com/1324583/185307007-14b419e0-b6b9-4d29-80b9-935bb4745d34.png)

2022-08-18 06:31 UTC, BerndHueckstaedt commented
Do the contriubution links not belong in the admin interface?

Gehören die Contriubution -Links gehören nicht ins Admin-Interface?

2022-08-18 10:16 UTC, ogerly commented
> Do the contriubution links not belong in the admin interface?
> 
> Gehören die Contriubution -Links gehören nicht ins Admin-Interface?

but you can also see them on the overveiw page ... where you can also see them.

2022-08-18 11:05 UTC, Tirokk requested changes
Hey @ogerly 🍀

This is a very important and nice feature you did !!! 🚀🚀💫💫

I have some suggestions:

! Please review the spanish locale @Mogge !

Is the short word `Info` optimal in German and English. I think `Information` is better in both languages.
Even the path should be `/information` I think.

We should have a circle around the "i" as I put in my code suggestions? See screenshot:

<img width="1646" alt="Bildschirmfoto 2022-08-18 um 11 56 21" src="https://user-images.githubusercontent.com/25344101/185367994-306aa6ac-9dd2-4e0b-a47b-5510656107a6.png">

2022-08-18 11:05 UTC, Tirokk commented on frontend/src/locales/en.json
> +    "info": "Info",
```suggestion
    "info": "Information",
```

Is much better in my eyes!

2022-08-18 11:05 UTC, Tirokk commented on frontend/src/locales/de.json
> +    "info": "Info",
```suggestion
    "info": "Information",
```

Is much better in my eyes!

2022-08-18 12:04 UTC, Mogge requested changes

2022-08-18 12:04 UTC, Mogge commented on frontend/src/locales/es.json
> +    "openContributionLinkText": "La comunidad {count} proporciona actualmente las siguientes \"{name}\" creaciones automáticas.",
```suggestion
    "openContributionLinkText": "La comunidad \"{name}\" proporciona actualmente las siguientes {count} creaciones automáticas.",
```

2022-08-18 15:14 UTC, Tirokk requested changes
Minor suggestion for english quotes …

2022-08-18 15:14 UTC, Tirokk commented on frontend/src/locales/en.json
> +    "openContributionLinkText": "The following {count} automatic creations are currently provided by the \"{name}\" community.",
```suggestion
    "openContributionLinkText": "The following {count} automatic creations are currently provided by the “{name}” community.",
```

2022-08-18 15:18 UTC, ogerly commented on frontend/src/locales/en.json
> +    "openContributionLinkText": "The following {count} automatic creations are currently provided by the \"{name}\" community.",
modified by hand

2022-08-18 15:32 UTC, Tirokk requested changes
Please these little changes again …

2022-08-18 15:37 UTC, Tirokk approved these changes
Yes !!!

I approve 🚀🚀💫💫

2022-08-18 15:54 UTC, merged