1910 separate text for the slideshow images.
gradido/gradido pull request #1998
Opened 2022-06-21 10:06 UTC by ogerly

## 🍰 Pullrequest
seperater text für die slideshow bilder. 

1. Dankbarkeit -  Die neue Währung. Für einander, für alle Menschen, für die Natur.
2. Würde - Wir Schenken einander und Danken mit Gradido.
3. Gabe - Du bist ein Geschenk für die Gemeinschaft. 1000 Dank, weil du bei uns bist.

___

1. Gratitude - The new currency. For each other, for all people, for nature.
2. Dignity - We give gifts to each other and give thanks with Gradido.
3. Donation - You are a gift for the community. 1000 thanks because you are with us.

### Issues
- fixes #1910 

https://user-images.githubusercontent.com/1324583/174774250-840afa4e-fa4e-4dd9-89c4-15038db4e91e.mp4

2022-06-22 13:07 UTC, Mogge requested changes

2022-06-22 13:07 UTC, Mogge commented on frontend/src/locales/de.json
> +      "oneDignity": "Wir Schenken einander und Danken mit Gradido.",
```suggestion
      "oneDignity": "Wir schenken einander und Danken mit Gradido.",
```

2022-06-22 13:07 UTC, Mogge commented on frontend/src/locales/de.json
> +      "oneDignity": "Wir Schenken einander und Danken mit Gradido.",
@BerndHueckstaedt bitte prüfen

2022-06-22 13:07 UTC, Mogge commented on frontend/src/locales/en.json
> +      "oneDignity": "We give gifts to each other and give thanks with Gradido.",
@BerndHueckstaedt bitte prüfen

2022-06-27 11:56 UTC, Mogge approved these changes
Wenn @BerndHueckstaedt mit den Texten eiverstanden ist, passt das für mich

2022-06-27 12:48 UTC, BerndHueckstaedt commented
Kleine Korrektur:
Würde - Wir schenken einander und danken mit Gradido. (schenken und danken klein geschrieben)

2022-06-27 13:47 UTC, Mogge approved these changes

2022-06-27 13:52 UTC, merged