[WIP] automatic session logout with info modal
gradido/gradido pull request #2001
Opened 2022-06-22 20:55 UTC by ogerly

## 🍰 Pullrequest
  es kann wie folgt getestet werden.
1. setze die zeit auf 2m (zwei Minuten) in **backend/src/config/index.ts**  Zeile: 28   

### Issues
 - fixes #1736 
 

![FireShot Capture 1224 -  - localhost](https://user-images.githubusercontent.com/1324583/175132959-add2415d-b974-4aa2-8839-ba18541b2ccf.png)

https://user-images.githubusercontent.com/1324583/175134223-735371fd-0ba8-471c-9282-94cdb0cf954f.mp4

2022-06-22 21:00 UTC, ogerly commented
I just noticed the following error: 
I have to stop the first interval in the time where the 60 seconds are counted down ... otherwise every 15 seconds a -1 is added. 
if you click on extend, the first interval must be restarted.

2022-06-23 05:16 UTC, ogerly commented
there is now also a hint sound every 13 seconds when the session expires ... even if the tab should run in the background. 
if we leave this in then should be given sometime in the settings for the user ... a way to turn this off. 
I chose it but so that it is not annoying. I find it discreet. that can of course be a matter of taste.
https://user-images.githubusercontent.com/1324583/175220439-4ab93b11-dc48-4721-a776-43feb937938c.mp4

2022-06-24 11:28 UTC, ogerly commented
![FireShot Capture 1226 -  - localhost](https://user-images.githubusercontent.com/1324583/175525640-3989bb84-9a18-4ad6-b849-d1b2f49f30d7.png)

2022-06-27 07:07 UTC, ogerly commented
![Bildschirmfoto vom 2022-06-27 09-05-03](https://user-images.githubusercontent.com/1324583/175880076-22e80ea7-828c-4274-9bb2-595886a6270d.png)

2022-06-27 08:29 UTC, ogerly commented
![image](https://user-images.githubusercontent.com/1324583/175895392-e52f0ee1-9e06-4c0f-9cb7-0fc434fcfb0c.png)

2022-06-30 12:09 UTC, Tirokk requested changes
Everything looks good in general.
But I have some suggestions …

2022-06-30 12:09 UTC, Tirokk commented on frontend/src/store/store.test.js
> +      describe('token has null value', () => {
```suggestion
      })
      
      describe('token has null value', () => {
```

2022-06-30 12:09 UTC, Tirokk commented on frontend/src/store/store.test.js
> +      describe('token has a value', () => {
```suggestion
      })
      
      describe('token has a value', () => {
```

2022-06-30 13:32 UTC, Mogge submitted a review, later dismissed

2022-06-30 13:53 UTC, merged