[WIP] add code for moving user creation date if transaction before exist
gradido/gradido pull request #2034
Opened 2022-07-05 15:10 UTC by einhornimmond

## 🍰 Pullrequest

### Issues

- None

### Todo

- [X] None

2022-07-06 09:20 UTC, Mogge reviewed
Looks good!

2022-07-07 11:37 UTC, Mogge requested changes
I suggest to rename the migration file to `0041-...`
So we can merge this one. To get it pass the CI tests, you have to update the `DB_VERSION` in `backend/src/config/index.ts`

2022-07-10 06:41 UTC, einhornimmond commented
> I suggest to rename the migration file to `0041-...` So we can merge this one. To get it pass the CI tests, you have to update the `DB_VERSION` in `backend/src/config/index.ts`

This get's the 42 because the 41 is already used from #2029, so than we can merge this one after merging the #2029

2022-07-11 11:53 UTC, Mogge approved these changes
I really suggest to merge this first.

2022-07-11 11:54 UTC, Mogge requested changes

2022-07-11 11:54 UTC, Mogge commented on backend/src/config/index.ts
> +  DB_VERSION: '0042-move_users_creation_date',
```suggestion
  DB_VERSION: '0041-move_users_creation_date',
```

2022-07-11 11:54 UTC, Mogge commented on database/migrations/0042-move_users_creation_date.ts
> +/* eslint-disable @typescript-eslint/explicit-module-boundary-types */
Change file name to `0041`

2022-07-11 13:09 UTC, einhornimmond commented on database/migrations/0042-move_users_creation_date.ts
> +/* eslint-disable @typescript-eslint/explicit-module-boundary-types */
> I really suggest to merge this first.

ok, should also work in this order.

2022-07-11 16:07 UTC, Mogge approved these changes

2022-07-11 21:40 UTC, merged