Feat: ContributionResolver - delete mutation
gradido/gradido pull request #2035
Opened 2022-07-06 07:33 UTC by Elweyn

## 🍰 Pullrequest
Method to delete a contribution

### Issues

- relates #2000

### Todo

- [X] None

2022-07-13 15:57 UTC, Mogge requested changes

2022-07-13 15:57 UTC, Mogge commented on backend/src/graphql/resolver/ContributionResolver.ts
> +  async adminDeleteContribution(
```suggestion
  async deleteContribution(
```

2022-07-13 15:58 UTC, Mogge requested changes

2022-07-18 11:05 UTC, Elweyn commented on backend/src/graphql/resolver/ContributionResolver.ts
> +  async adminDeleteContribution(
Change the name

2022-07-18 11:05 UTC, Elweyn commented on backend/src/graphql/resolver/ContributionResolver.ts
>  import ContributionArgs from '../arg/ContributionArgs'
Has been resolved through merging master

2022-07-19 07:05 UTC, Tirokk approved these changes
Looks really good to me! 🚀💫

I approve! 🍀

2022-07-19 10:23 UTC, Mogge commented on backend/src/graphql/resolver/ContributionResolver.test.ts
> +      })
There is a call `adminDeleteContribution` @Tirokk

2022-07-19 10:26 UTC, Elweyn commented on backend/src/graphql/resolver/ContributionResolver.test.ts
> +      })
Yes for admins we have ``adminDeleteContribution`` and for users we have ``deleteContribution``
A User can only delete his contribution, an Admin can also delete contributions of other users

2022-07-19 10:27 UTC, Mogge requested changes

2022-07-19 10:27 UTC, Mogge commented on backend/src/graphql/resolver/ContributionResolver.test.ts
> +      describe('User deletes own contribution', () => {
Please add a test where you confirm the contribution and check, that a confirmed contribution cannot be deleted.

2022-07-19 10:27 UTC, Mogge commented on backend/src/graphql/resolver/ContributionResolver.ts
> +    }
```
if (contribution.confirmedAt) throw new Error('A confirmed contribution cannot be deleted.')

2022-07-19 10:39 UTC, Elweyn commented on backend/src/graphql/resolver/ContributionResolver.ts
> +    }
OK I make this

2022-07-19 11:49 UTC, Mogge approved these changes

2022-07-19 12:01 UTC, merged