2119 new menu item gdt
gradido/gradido pull request #2120
Opened 2022-08-07 11:24 UTC by ogerly

## 🍰 Pullrequest
there is now a separate router entry for transaction and gradido transform. 

### Issues
- fixes #2119 

https://user-images.githubusercontent.com/1324583/183287860-d3c99143-8da6-40f6-8359-0194a66a92a6.mp4

2022-08-10 14:07 UTC, Mogge requested changes
Wow. What a hack.

2022-08-10 14:07 UTC, Mogge commented on frontend/src/pages/Transactions.spec.js
> +import flushPromises from 'flush-promises'
Why?

2022-08-11 12:24 UTC, ogerly commented on frontend/src/pages/Transactions.spec.js
> +import flushPromises from 'flush-promises'
flushPromises deleted

2022-08-11 12:25 UTC, ogerly commented on frontend/src/pages/Transactions.spec.js
> +              flushPromises()
flushPromises deleted

2022-08-11 12:35 UTC, ogerly commented
> 

it would be conceivable to remove the tab system and create separate pages for each ...

2022-08-16 08:29 UTC, Mogge requested changes

2022-08-16 08:29 UTC, Mogge commented on frontend/src/components/GddSend/TransactionConfirmationLink.spec.js
> +      it('has button disable', () => {
```suggestion
      it('has send button disabled', () => {
```

2022-08-16 08:29 UTC, Mogge commented on frontend/src/components/GddSend/TransactionConfirmationLink.spec.js
> +    describe('has totalBalance under 0', () => {
```suggestion
    describe('has total balance equal 0', () => {
```

2022-08-16 08:58 UTC, Tirokk approved these changes
Hey @ogerly 
works fine!

Great 🚀💫
I approve!

2022-08-16 09:39 UTC, Tirokk approved these changes
Now I approve again.

2022-08-16 09:46 UTC, merged