2121 translate locales to spanish
gradido/gradido pull request #2122
Opened 2022-08-07 20:46 UTC by ogerly

## 🍰 Pullrequest
Add locales Español

### Issues
 - fixes #2121
 

https://user-images.githubusercontent.com/1324583/183310355-b03809fe-5241-458b-9e88-107210cdcc8b.mp4

2022-08-09 12:22 UTC, Mogge requested changes
Ich empfehle generell `Importe` statt `Monto` zu verwenden. Was meint die Übersetzerin?

2022-08-09 12:22 UTC, Mogge commented on frontend/src/locales/es.json
> +      "communityNoteList": "Aquí encontrarás todas las contribuciones enviadas y confirmadas de todos los miembros de esta comunidad..",
```suggestion
      "communityNoteList": "Aquí encontrarás todas las contribuciones enviadas y confirmadas de todos los miembros de esta comunidad.",
```

2022-08-09 12:22 UTC, Mogge commented on frontend/src/locales/es.json
> +      "myContributionNoteList": "Puedes editar o eliminar las contribuciones enviadas que aún no han sido confirmadas en cualquier momento..",
```suggestion
      "myContributionNoteList": "Puedes editar o eliminar las contribuciones enviadas que aún no han sido confirmadas en cualquier momento.",
```

2022-08-09 12:22 UTC, Mogge commented on frontend/src/locales/es.json
> +      "myContributionNoteSupport": "Pronto existirá la posibilidad de que puedas dialogar con los moderadores. Si tienes algún problema ahora, ponte en contacto con el equipo de asistencia..",
```suggestion
      "myContributionNoteSupport": "Pronto existirá la posibilidad de que puedas dialogar con los moderadores. Si tienes algún problema ahora, ponte en contacto con el equipo de asistencia.",
```

2022-08-09 12:22 UTC, Mogge commented on frontend/src/locales/es.json
> +      "bringYourTalentsTo": "¡Contribuye a la comunidad con tus talentos! Premiamos tu compromiso voluntario con 20 GDD por hora hasta un máximo de 1.000 GDD al mes..",
```suggestion
      "bringYourTalentsTo": "¡Contribuye a la comunidad con tus talentos! Premiamos tu compromiso voluntario con 20 GDD por hora hasta un máximo de 1.000 GDD al mes.",
```

2022-08-09 12:22 UTC, Mogge commented on frontend/src/locales/es.json
> +      "maxGDDforMonth": "Sólo puede presentar un máximo de {amount} GDD para el mes seleccionado..",
```suggestion
      "maxGDDforMonth": "Sólo puede presentar un máximo de {amount} GDD para el mes seleccionado.",
```

2022-08-09 12:22 UTC, Mogge commented on frontend/src/locales/es.json
> +      "hereLogin": "Registrate aquí",
```suggestion
      "hereLogin": "Regístrate aquí",
```

2022-08-09 12:22 UTC, Mogge commented on frontend/src/locales/es.json
> +      "learnMore": "Informate aquí …",
```suggestion
      "learnMore": "Infórmate aquí …",
```

2022-08-09 12:22 UTC, Mogge commented on frontend/src/locales/es.json
> +    "yourActivity": "¡Por favor, introduzca una actividad!"
```suggestion
    "yourActivity": "¡Por favor, introduce una actividad!"
```

2022-08-09 12:22 UTC, Mogge commented on frontend/src/locales/es.json
> +    "app_version": "App version {version}",
```suggestion
    "app_version": "App versión {version}",
```

2022-08-09 12:23 UTC, Mogge commented
Was ist mit den Datums und Number-Definitionen?

2022-08-09 12:27 UTC, ogerly commented
> Ich empfehle generell `Importe` statt `Monto` zu verwenden. Was meint die Übersetzerin?

ich glaube sie liest hier nicht mit ..

2022-08-09 12:30 UTC, ogerly commented on frontend/src/locales/es.json
> +    "activateEmail": "Tu cuenta aún no ha sido activada. Por favor revisa tu correo electrónico y haz clic en el enlace de activación o solicita uno nuevo Aktivierungslink über die Password Reset Sei
deeple würde aus dem english so übersetzen: 

**Su cuenta aún no ha sido activada. Por favor, compruebe sus correos electrónicos y haga clic en el enlace de activación o solicite un nuevo enlace de activación a través de la página de restablecimiento de contraseña.**

2022-08-10 13:58 UTC, Mogge approved these changes

2022-08-11 08:58 UTC, merged