2116 retrieve admin and moderators
gradido/gradido pull request #2127
Opened 2022-08-10 09:29 UTC by Elweyn

## 🍰 Pullrequest

As User we want to see the moderators and admins of the community

### Issues

- fixes #2116 

### Todo

- [X] Implement resolver method to query moderators and admins

2022-08-16 08:27 UTC, Mogge requested changes
What about a simple test?

2022-08-16 08:27 UTC, Mogge commented on backend/src/graphql/resolver/UserResolver.ts
> +    }
I think this is not needed.

2022-08-16 08:27 UTC, Mogge commented on backend/src/graphql/resolver/UserResolver.ts
> +    }
```suggestion
    return {
      userCount: count,
      userList: users.map((user) => {
        return {
          firstName: user.firstName,
          lastName: user.lastName,
        },
    }
```

2022-08-16 08:27 UTC, Mogge commented on backend/src/graphql/resolver/UserResolver.ts
> +    )
Not needed

2022-08-17 12:07 UTC, ogerly commented
this PR is part noted in #1973 , works and goes !

2022-08-17 13:19 UTC, Mogge approved these changes

2022-08-17 13:20 UTC, merged