2135 add the languages french and dutch
gradido/gradido pull request #2138
Opened 2022-08-16 09:59 UTC by ogerly

## 🍰 Pullrequest
add locales french and dutch

### Issues
- fixes #2135 
 

![Bildschirmfoto vom 2022-08-16 11-29-06](https://user-images.githubusercontent.com/1324583/184852508-dcff58a3-0521-4914-8cb5-eb941b019052.png)

2022-08-16 10:42 UTC, BerndHueckstaedt commented
I had understood Christopher's design so that the current language is on the left and the other languages can be selected in a drop-down menu. This is what the triangle was meant for.

ich hatte den Entwurf von Christopher so verstanden, dass die aktuelle Sprache links steht und die jeweils anderen Sprachen in einem Aufklapp-Menü ausgewählt werden können. Dafür war das Dreieck gedacht.

2022-08-16 11:41 UTC, Mogge requested changes
Please clean up. Remove everything that is not related lo locales.

2022-08-16 11:44 UTC, ogerly commented
> Please clean up. Remove everything that is not related lo locales.

oh ... somehow the statistics got in there

2022-08-16 12:45 UTC, ogerly commented
> I had understood Christopher's design so that the current language is on the left and the other languages can be selected in a drop-down menu. This is what the triangle was meant for.
> 
> ich hatte den Entwurf von Christopher so verstanden, dass die aktuelle Sprache links steht und die jeweils anderen Sprachen in einem Aufklapp-Menü ausgewählt werden können. Dafür war das Dreieck gedacht.

is changed

2022-08-16 13:20 UTC, Elweyn requested changes

2022-08-16 13:20 UTC, Elweyn commented on frontend/src/locales/fr.json
> +    "choose-amount": "Sélectionnez le montant que vous souhaitez envoyer via le lien. Vous pouvez également joindre un message. Cliquez sur ‘créer maintenant’ pour établir un lien que vous pourrez pa
```suggestion
    "choose-amount": "Sélectionnez le montant que vous souhaitez envoyer via lien. Vous pouvez également joindre un message. Cliquez sur ‘créer maintenant’ pour établir un lien que vous pourrez partager.",
```

2022-08-16 13:20 UTC, Elweyn commented on frontend/src/locales/fr.json
> +    "delete-the-link": " Supprimer le lien?",
```suggestion
    "delete-the-link": "Supprimer le lien?",
```

2022-08-16 13:20 UTC, Elweyn commented on frontend/src/locales/fr.json
> +    "links_sum": "Ouvrir les liens et les codes QR",
```suggestion
    "links_sum": "Ouvrir les liens et les QR codes",
```

2022-08-16 13:20 UTC, Elweyn commented on frontend/src/locales/fr.json
> +    "not-copied": "Malheureusement votre appareil ne permet pas de copier ! Veuillez copier le lien  manuellement svp!",
```suggestion
    "not-copied": "Malheureusement votre appareil ne permet pas de copier! Veuillez copier le lien manuellement svp!",
```

2022-08-16 13:20 UTC, Elweyn commented on frontend/src/locales/fr.json
> +    "redeem": " Encaisser",
```suggestion
    "redeem": "Encaisser",
```

2022-08-16 13:20 UTC, Elweyn commented on frontend/src/locales/fr.json
> +    "redeemed-at": " Le lien a déjà été perçu le {date}.",
```suggestion
    "redeemed-at": "Le lien a déjà été perçu le {date}.",
```

2022-08-16 13:20 UTC, Elweyn commented on frontend/src/locales/fr.json
> +    "redeemed-title": "encaisser ",
```suggestion
    "redeemed-title": "encaisser",
```

2022-08-16 13:20 UTC, Elweyn commented on frontend/src/locales/fr.json
> +    "redeemed": "Encaissé avec succès ! Votre compte est crédité de {n} GDD.",
```suggestion
    "redeemed": "Encaissé avec succès! Votre compte est crédité de {n} GDD.",
```

2022-08-16 13:20 UTC, Elweyn commented on frontend/src/locales/fr.json
> +  "qrCode": "Code QR",
```suggestion
  "qrCode": "QR Code",
```

2022-08-16 13:20 UTC, Elweyn commented on frontend/src/locales/fr.json
> +    "lightText": "S´il n´apparaît aucune activité   pendant plus de 10 minutes, la session expirera pour des raisons de sécurité.",
```suggestion
    "lightText": "S´il n´apparaît aucune activité pendant plus de 10 minutes, la session expirera pour des raisons de sécurité.",
```

2022-08-16 13:20 UTC, Elweyn commented on frontend/src/locales/fr.json
> +    "logoutIn": "Se déconnecter ",
```suggestion
    "logoutIn": "Se déconnecter",
```

2022-08-16 13:45 UTC, Mogge requested changes

2022-08-16 13:45 UTC, Mogge commented on frontend/src/locales/de.json
> +      "fr": "French",
```suggestion
      "fr": "Français",
```

2022-08-16 13:45 UTC, Mogge commented on frontend/src/locales/en.json
> +      "fr": "French",
```suggestion
      "fr": "Français",
```

2022-08-16 13:45 UTC, Mogge commented on frontend/src/locales/en.json
> +      "es": "Spanish",
```suggestion
      "es": "Español",
```

2022-08-16 13:45 UTC, Mogge commented on frontend/src/locales/en.json
> +      "nl": "Dutch",
```suggestion
      "nl": "Holandés",
```

2022-08-16 13:45 UTC, Mogge commented on frontend/src/locales/index.js
> +    name: 'French',
```suggestion
    name: 'Français',
```

2022-08-16 13:45 UTC, Mogge commented on frontend/src/locales/index.js
> +    name: 'Dutch',
```suggestion
    name: 'Holandés',
```

2022-08-17 08:06 UTC, Tirokk requested changes
Changes in NL …

2022-08-17 09:05 UTC, Tirokk requested changes
I would refine the design a bit, see at the end.

And there are kind of design errors as well.
In `Holandés` the pipe between the choosen language and the arrow is missing. And there is a pipe to much after the last language if you open the menu:

<img width="1646" alt="Bildschirmfoto 2022-08-17 um 10 45 25" src="https://user-images.githubusercontent.com/25344101/185078017-7f1b5e7f-8725-4df1-b5aa-5dcb91eccd3b.png">

I would consider:

- to completely remove the pipe between the choosen language and the arrow and put the arrow directly aside the lange and have both clickable to open the menu.
- or to have english always additional on the right side of the pipe. Then have a second pipe with `Others` and the arrow aside it and have both clickable to oppen the menu.

<img width="1646" alt="Bildschirmfoto 2022-08-17 um 10 44 16" src="https://user-images.githubusercontent.com/25344101/185078066-2491d254-4c09-4385-b858-d9af2e448bb5.png">

2022-08-17 12:02 UTC, ogerly commented
@Tirokk i have adjusted this. however, when i select dutch hiter french is a pipe ... this is a bit more complicated than i thought. i need to look at this with more musse. otherwise it fits quite well now ... 
https://user-images.githubusercontent.com/1324583/185113267-f1e93f1a-a772-44e2-a098-6b7dd2c1041d.mp4

2022-08-18 15:51 UTC, Tirokk submitted a review, later dismissed
Yes !!!

I approve 🚀🚀💫💫

2022-08-18 17:05 UTC, ogerly commented
close menu when selected another language

https://user-images.githubusercontent.com/1324583/185453161-587fd123-93fc-4bd8-9d53-87281a8516d9.mp4

2022-08-19 09:54 UTC, Elweyn requested changes

2022-08-19 09:54 UTC, Elweyn commented on frontend/src/locales/fr.json
> +    "totalGradidoCreated": "GDD total épuisé",
Épuisé bedeutet erschöpft! Soll aber wohl geschöpft heißen oder? Wenn ja dann:
```suggestion
    "totalGradidoCreated": "GDD total puisé",
```

2022-08-19 09:54 UTC, Elweyn commented on frontend/src/locales/fr.json
> +    "totalGradidoDecayed": "GDD total annulé",
```suggestion
    "totalGradidoDecayed": "Total de GDD écoulé",
```

2022-08-19 09:54 UTC, Elweyn commented on frontend/src/locales/fr.json
> +    "totalGradidoUnbookedDecayed": "Total GDD non comptabilisé Expiration"
```suggestion
    "totalGradidoUnbookedDecayed": "Total GDD non comptabilisé écoulé"
```

2022-08-19 10:03 UTC, Elweyn approved these changes

2022-08-19 11:33 UTC, Mogge approved these changes

2022-08-19 12:20 UTC, merged