2095 send email contribution confirmed
gradido/gradido pull request #2193
Opened 2022-09-12 09:44 UTC by Elweyn

## 🍰 Pullrequest

Als User möchte ich eine EMail erhalten wenn mein Schöpfung Antrag bestätigt wurde

### Issues

- fixes #2095 

### Todo

- [X] None

2022-09-13 12:45 UTC, Mogge requested changes

2022-09-13 12:45 UTC, Mogge commented on backend/src/mailer/text/contributionConfirmed.ts
> +Deine Gradido Schöpfungsantrag "${data.contributionMemo}" wurde soeben von ${
```suggestion
Dein Gradido Schöpfungsantrag "${data.contributionMemo}" wurde soeben von ${
```

2022-09-13 12:45 UTC, Mogge commented on backend/src/mailer/sendContributionConfirmedEmail.test.ts
> +          'Deine Gradido Schöpfungsantrag "Vielen herzlichen Dank für den neuen Hexenbesen!" wurde soeben bestätigt.',
```suggestion
          'Dein Gradido Schöpfungsantrag "Vielen herzlichen Dank für den neuen Hexenbesen!" wurde soeben von Peter Lustig bestätigt.',
```

2022-09-15 08:52 UTC, Mogge approved these changes

2022-09-15 14:56 UTC, Tirokk approved these changes
I didn't test manually, but I approve, because it was just an easy merg conflict. 🍀

2022-09-15 14:57 UTC, merged