docu: [WIP] 🍰 Refine Deployment Documentation
gradido/gradido pull request #2209
Opened 2022-09-15 13:36 UTC by Tirokk

## 🍰 Pullrequest

Refine deployment documentation.

### Issues

- fixes #2208

### Todo

- [ ] … I think

2022-09-27 10:52 UTC, Mogge requested changes

2022-09-27 12:10 UTC, Tirokk commented on deployment/bare_metal/setup.md
> +
I wrote a text infront of the command.
Please have a look.

2022-09-27 12:12 UTC, Tirokk commented on deployment/bare_metal/setup.md
> +# Will result in in either a password request for your key or the message 'Permission denied (publickey)'
Yup!
Done

2022-09-28 21:18 UTC, Mogge approved these changes
Thanks a lot. I really appreciate that you care about the documentation!

2022-09-29 07:02 UTC, merged