Bug: delete contribution link
gradido/gradido pull request #2213
Opened 2022-09-16 10:18 UTC by ogerly

## 🍰 Pullrequest
a contribution link can be deleted. 
Automatic reloading of the contribution list when a delete or create has run.

### Issues
- fixes #2109 
 
 

https://user-images.githubusercontent.com/1324583/190616911-e277b3a3-ef9d-4b0d-b7ed-1ef01cbf311c.mp4

2022-09-22 07:19 UTC, Mogge requested changes

2022-09-22 07:19 UTC, Mogge commented on admin/src/locales/de.json
> +    "deleteNow": "Automatische Creations '{name}' wirklich löschen?",
```suggestion
    "deleteNow": "Automatische Schöpfung '{name}' löschen?",
```

2022-09-22 07:19 UTC, Mogge commented on admin/src/locales/en.json
> +    "deleteNow": "Do you really delete automatic creations '{name}'?",
```suggestion
    "deleteNow": "Delete automatic creations '{name}'?",
```

2022-09-22 07:19 UTC, Mogge commented on admin/src/components/ContributionLinkList.vue
> +                this.toastSuccess('TODO: request message deleted ')
Please have a message

2022-09-22 07:19 UTC, Mogge commented on admin/src/components/ContributionLinkList.vue
> +                this.toastSuccess('TODO: request message deleted ')
Automatische Schöpfung gelöscht!

2022-09-22 07:19 UTC, Mogge commented on admin/src/components/ContributionLink.vue
> +            @get-contribution-links="getContributionLinks"
```suggestion
            @get-contribution-links="$emit('get-contribution-links')"
```

2022-09-22 07:19 UTC, Mogge commented on admin/src/components/ContributionLink.vue
> +          @get-contribution-links="getContributionLinks"
```suggestion
          @get-contribution-links="$emit('get-contribution-links')"
```

2022-09-22 07:19 UTC, Mogge commented on admin/src/components/ContributionLink.vue
> +    },
```suggestion
```

2022-09-22 08:03 UTC, ogerly commented on admin/src/components/ContributionLinkList.vue
> +                this.toastSuccess('TODO: request message deleted ')
done

2022-09-27 11:16 UTC, Mogge approved these changes

2022-09-29 12:50 UTC, merged