Refactor: Test register with redeem code
gradido/gradido pull request #2214
Opened 2022-09-16 11:55 UTC by jjimenezgarcia

## 🍰 Pullrequest
- Added test for event redeem register when using a contribution link
- Fixed date handling issue as in #2204 to avoid code discrepancies when merging

### Issues
- fixes #2207

### Todo

- [] Fix transaction link test (still don't know if problem is in test implementation or in logic itself)

2022-09-19 13:31 UTC, Mogge requested changes

2022-09-19 13:31 UTC, Mogge commented on backend/src/graphql/resolver/UserResolver.test.ts
> +        it('sets the referrer id to Peter Lustigs id', () => {
And once more, test for the redeem register event (with transaction id set)

2022-09-19 17:16 UTC, jjimenezgarcia commented on backend/src/graphql/resolver/UserResolver.ts
> +      const eventActivateAccount = new EventActivateAccount()
isn't it where it has to be already? can't see another placement. What do you mean by inside the transaction?

2022-09-22 12:02 UTC, Mogge approved these changes
Great!

2022-09-22 12:20 UTC, merged