Refactor: Add all events to documentation table
gradido/gradido pull request #2240
Opened 2022-09-26 20:45 UTC by jjimenezgarcia

## 🍰 Pullrequest
Added all new events to documentation table 

Events implemented on #2231

### Issues
- relates #2205 

### Todo
- [X] None

2022-09-28 19:18 UTC, clauspeterhuebner approved these changes
One small change should be done before merge...
Good work.

2022-09-28 19:18 UTC, clauspeterhuebner commented on docu/Concepts/TechnicalRequirements/BusinessEventProtocol.md
> +| VERIFY_REDEEM                     | VerifyRedeemEvent                      |  x  |   x   |     x     |    x    |        |              |       (x)       |      (x)    |        |
Ok that's a good idea to add here for the new eventtypes the new eventkeys.
But then please change the column headlines too
1. column: EventKey
2. column: EventType

2022-09-28 21:12 UTC, Mogge requested changes
Please add the header of the table as indicated by Claus-Peter

2022-10-10 12:44 UTC, Mogge approved these changes

2022-10-11 10:11 UTC, merged