Bug fix: Verify Token Before Redeeming a Link
gradido/gradido pull request #2254
Opened 2022-10-07 09:02 UTC by mahula

## 🍰 Pullrequest
Before going to the redeem page, the token has to be verified.
In this case the expiration time of the token should be cheked.

### Issues
- fixes #2069

### Todo
- [X]  Implement check for valid expiration time in Vue page TransactionLink
- [X] Adapt the unit tests

2022-10-10 12:50 UTC, Mogge requested changes

2022-10-12 07:28 UTC, mahula commented on frontend/src/pages/TransactionLink.spec.js
> +        mocks.$store.state.token = jwt.sign({ data: 'test' }, 'secret', { expiresIn: '1h' })
This was utilized to achieve a realistic token expiration time for the tests related to token time.

2022-10-12 11:07 UTC, mahula commented on frontend/package.json
> +    "jsonwebtoken": "^8.5.1",
Right.

2022-10-12 11:08 UTC, mahula commented on frontend/src/pages/TransactionLink.spec.js
> +        mocks.$store.state.token = jwt.sign({ data: 'test' }, 'secret', { expiresIn: '1h' })
This has been fixed by [00e7ea7](https://github.com/gradido/gradido/commit/00e7ea776de61323fd38e436d8907efb6b0d690f).

2022-10-12 15:30 UTC, Mogge approved these changes

2022-10-12 15:31 UTC, merged