2315 the last and current month is displayed cleanly again.
gradido/gradido pull request #2316
Opened 2022-10-31 14:07 UTC by ogerly

## 🍰 Pullrequest
the last and current month is displayed cleanly again. 

### Issues
- fixes #2315 

![image](https://user-images.githubusercontent.com/1324583/199027221-38f4f698-978f-436a-876b-b1044a32a436.png)

2022-10-31 18:17 UTC, Mogge requested changes
The tests were good, they do what they should. Add a test case for 31.10.2022

2022-10-31 18:17 UTC, Mogge commented on frontend/src/components/Contributions/ContributionForm.vue
> +      return new Date(date.getFullYear(), date.getMonth() - 1)
```
     minimalDate() {
       const date = new Date(this.maximalDate)
       return new Date(date.setMonth(date.getMonth() - 1, 1))
     },
```

2022-10-31 18:25 UTC, Mogge commented
Add another test case for 28.2.2023

2022-11-01 05:40 UTC, ogerly commented
the problem is the 31st of a month ... minus one month there is no 31st. here lies the problem

2022-11-01 08:02 UTC, Mogge commented
My code suggestion above solves the problem, @ogerly

2022-11-01 10:26 UTC, ogerly commented on frontend/src/components/Contributions/ContributionForm.vue
> +      return new Date(date.getFullYear(), date.getMonth() - 1)
done

2022-11-01 10:27 UTC, ogerly commented
i have more tests for: 
- date with the 31st day of the month
- date with the 28th day of the month
- date with 29.02.2024 leap year

2022-11-01 13:42 UTC, Mogge approved these changes

2022-11-01 13:53 UTC, merged