feat(backend): 🍰 Mark creation via link
gradido/gradido pull request #2363
Opened 2022-11-10 09:55 UTC by Elweyn

## 🍰 Pullrequest

If the creation is created via Link then shows a text to mark it

### Issues

- fixes #2285 

### Todo

- [X] None

2022-11-10 13:36 UTC, ulfgebhardt requested changes

2022-11-10 13:36 UTC, ulfgebhardt commented on backend/src/graphql/resolver/TransactionLinkResolver.ts
> +        transaction.transactionLinkId = contributionLink.id
```suggestion
        transaction.linkId = contributionLink.id
```

Please correct the field name to `linkId` - this is more clear then that the transaction type defines the context of the linkId (either transactionLinkId or contributionLinkid)

2022-11-10 13:36 UTC, ulfgebhardt commented on backend/src/graphql/resolver/TransactionLinkResolver.ts
> +        transaction.transactionLinkId = contributionLink.id
@Mogge Please give us feedback on this!

2022-11-10 20:10 UTC, ulfgebhardt commented on backend/src/graphql/resolver/TransactionLinkResolver.ts
> +        transaction.transactionLinkId = contributionLink.id
After talking to @Mogge the following:
You cannot write the `contributionLink.id` into the field `transaction.transactionLinkId`. You must join on the query  the transaction table with the contribution table. There is the field `contributionLinkId` available.

In the GraphQL Interface you can merge both fields to a `linkId` field and handle it like you did in the client.

Meaning: You can leave the client as it is except the naming of the field - you have to adjust the backend and join with contributions table.

2022-12-01 18:10 UTC, Mogge submitted a review, later dismissed
Looks very good! I have little changes

2022-12-02 06:31 UTC, Elweyn commented on database/entity/0052-add_updated_at_to_contributions/Transaction.ts
> +  @JoinColumn({ name: 'id', referencedColumnName: 'transactionId' })
No it does not work , problem is that the field transaction_id on the Contribution table.
With ``@JoinColumn({ name: 'id', referencedColumnName: 'transactionId' })`` we join with Transaction.id = Contribution.transactionId what we want.

2022-12-06 09:38 UTC, ulfgebhardt commented on backend/src/graphql/model/Transaction.ts
> +    this.transactionLinkId = transaction.contribution
if you combine it please name it `linkId`. If you do not combine it have both fields

2022-12-06 09:38 UTC, ulfgebhardt commented on backend/src/graphql/resolver/TransactionLinkResolver.ts
>          const creations = await getUserCreation(user.id, clientTimezoneOffset)
revert changes on this file. You do not change things here.

2022-12-06 09:38 UTC, ulfgebhardt commented on database/entity/0052-add_updated_at_to_contributions/Contribution.ts
>    JoinColumn,
change for `database/entity/contribution.ts` is missing

2022-12-06 11:25 UTC, ulfgebhardt approved these changes

2022-12-06 11:34 UTC, merged