refactor(admin): update yarn.lock file of admin.
gradido/gradido pull request #2579
Opened 2023-01-19 10:31 UTC by Elweyn

## 🍰 Pullrequest

### Issues

- None

### Todo

- [X] None

2023-01-19 11:25 UTC, Mogge requested changes
Please do the same for frontend and backend

2023-01-19 11:26 UTC, Mogge commented
Is this the browser list?

2023-01-23 10:32 UTC, Elweyn commented
@Mogge No it only updates 'caniuse-lite'.
I did update backend, frontend, database and the other folders but their was nothing to update for me!

2023-01-24 14:03 UTC, Mogge approved these changes

2023-01-24 14:03 UTC, merged