refactor(frontend): style refactor mobil auth area
gradido/gradido pull request #2643
Opened 2023-01-31 15:29 UTC by ogerly

## 🍰 Pullrequest
style refactor mobil auth area

### Issues
- fixes #2598 

![Bildschirmfoto vom 2023-01-31 16-12-59](https://user-images.githubusercontent.com/1324583/215803130-5f63531f-f72e-4220-a1da-8e90063d14d9.png)
![Bildschirmfoto vom 2023-01-31 16-12-50](https://user-images.githubusercontent.com/1324583/215803135-32c65619-9e9d-466c-ac91-a82eb6aefdde.png)
![Bildschirmfoto vom 2023-01-31 16-12-42](https://user-images.githubusercontent.com/1324583/215803137-67fec7f6-e512-4550-a27f-3e71b104bd22.png)

2023-02-01 16:09 UTC, Mogge requested changes

2023-02-01 16:09 UTC, Mogge commented on frontend/src/pages/Login.vue
> +          <!-- <div class="mt-5">
Do we need this comment?

2023-02-09 16:28 UTC, ogerly commented on frontend/src/pages/Login.vue
> +          <!-- <div class="mt-5">
done

2023-02-14 11:50 UTC, Mogge approved these changes

2023-02-14 23:01 UTC, merged