refactor(frontend): style and design changes to a contribution
gradido/gradido pull request #2648
Opened 2023-02-01 13:06 UTC by ogerly

## 🍰 Pullrequest
Display of an edited contribution improved

### Issues
- fixes #2562 

![Bildschirmfoto vom 2023-02-01 13-54-03](https://user-images.githubusercontent.com/1324583/216051022-5a8d94c3-431e-4395-871c-e32bb3fb7d63.png)

2023-02-07 00:18 UTC, ulfgebhardt commented
Great improvement!

I would like to have the entry changes with a different background color. I suggest a faint green.

2023-02-14 11:55 UTC, Mogge requested changes

2023-02-14 11:55 UTC, Mogge commented on frontend/src/locales/de.json
> +    "oldContribution": "Alter Beitrag",
```suggestion
    "oldContribution": "Vorherige Version",
```

2023-02-14 11:55 UTC, Mogge commented on frontend/src/locales/en.json
> +    "oldContribution": "Old post",
```suggestion
    "oldContribution": "Previous version",
```

2023-02-28 18:01 UTC, Mogge requested changes
I do not know why I did not see this on the first glance ...

2023-02-28 18:01 UTC, Mogge commented on frontend/src/locales/de.json
> +    "isEdited": "hat seinen Beitrag bearbeitet",
```suggestion
    "isEdited": "hat den Beitrag bearbeitet",
```

2023-02-28 18:01 UTC, Mogge commented on frontend/src/locales/en.json
> +    "isEdited": "edited his contribution",
```suggestion
    "isEdited": "edited the contribution",
```

2023-03-02 14:10 UTC, merged