refactor(backend): use LogError on creations
gradido/gradido pull request #2677
Opened 2023-02-07 20:18 UTC by ulfgebhardt

## 🍰 Pullrequest

fix logger on TransactionResolver

### Issues

- contributes to wrenchhttps://github.com/gradido/gradido/issues/2487
- contributes to boomhttps://github.com/gradido/gradido/issues/1870
- based on https://github.com/gradido/gradido/pull/2676

### Todo

- [X] None

2023-02-15 13:53 UTC, Elweyn requested changes

2023-02-15 13:53 UTC, Elweyn commented on backend/src/graphql/resolver/TransactionLinkResolver.test.ts
> +            ) */
Please delete this

2023-02-17 07:41 UTC, Elweyn approved these changes

2023-02-17 08:42 UTC, Mogge approved these changes

2023-02-17 10:33 UTC, merged