refactor(backend): event protocol rework
gradido/gradido pull request #2691
Opened 2023-02-10 02:49 UTC by ulfgebhardt

## 🍰 Pullrequest

Rework the event protocol.

The main changes are:
- Introduce an universal `EVENT()` function
- Have specialized functions for each event `EVENT_SOME_TYPE()` with specific what data is required for that event

![image](https://user-images.githubusercontent.com/1238238/217990059-707bb7d1-6ea4-40f1-8435-4c0db7a5e61f.png)

![image](https://user-images.githubusercontent.com/1238238/217990129-bbb20a3e-283a-415b-81db-be1d9559b7e4.png)

This should be fixed with the deny test

### Issues

- fixes #1870 

### Todo

- [ ] Ensure every event is tested for to be in the database

2023-02-10 13:39 UTC, Mogge requested changes
Please no to dos. If you do not want the same event, create a new one for admin send activation mail

2023-02-10 13:39 UTC, Mogge commented on backend/src/graphql/resolver/UserResolver.ts
> +      // TODO: this event is used twice, why?
This is admin sending confirmation email

2023-02-10 13:39 UTC, Mogge commented on backend/src/graphql/resolver/UserResolver.ts
> +      // TODO: this event is used twice, why?
This is registration email

2023-02-13 13:01 UTC, Elweyn reviewed
Good changes. 
Would only need to discuss if we want a better way of distinction between the following two:
- ``EVENT`` => Creating an DbEvent
- ``EVENT_*`` => Creating an EVENT & using save on the created object.

Maybe have like before a write function: ``write(EVENT_*())``
Or rename the functions: ``saveEVENT_*``

2023-02-14 00:50 UTC, ulfgebhardt commented on backend/src/graphql/resolver/ContributionResolver.ts
> +      contributionToUpdate.userId,
I changed this to `moderator.id`.

I believe that we need a better concept for the events overall - something like "We always log the account interacted with" - "if its a moderator, we log him aswell" - "we can link events" - stuff like that need a better concept, but I rather not do that in this PR.

Lets have a discussion on how we should proceed here.

My suggestion is:
- clarify if `EVENT` and `EVENT_SOME_TYPE` can have distinct different behaviour.
- merge this a good step into the right direction and have things visualized as a next step down that road, so investigation becomes easier.

2023-02-14 12:12 UTC, Mogge requested changes

2023-02-14 12:12 UTC, Mogge commented on backend/src/graphql/resolver/ContributionResolver.ts
> +      moderator.id,
I do not agree with this change. Yes, we do not have events of this kind so far. But the user stored in the database should be the one the action affects.

2023-02-14 12:12 UTC, Mogge commented on backend/src/graphql/resolver/ContributionResolver.ts
> +      moderator.id,
On admin delete we have stored the affected user as well. For consistency reasons, I want to see the user here as well

2023-02-14 15:52 UTC, Mogge approved these changes

2023-02-14 16:11 UTC, merged