refactor(workflow): configure jest to directly check coverage to schlanken the test workflows
gradido/gradido pull request #2790
Opened 2023-03-07 16:11 UTC by mahula

## 🍰 Pullrequest
We can configure jest to directly check coverage at the end of unit testing.
This makes the separate coverage check steps in our workflows obsolete.

### Todo
- [X] add `coveragaThreshold` to all `jest.condig.js`
- [X] remove separate coverage check steps from github test wirkflows
- [ ] remove the coverage checks from the branch protection, @ulfgebhardt

2023-03-07 17:29 UTC, Mogge requested changes
Please ensure that `collectCoverage: true` is set in all jest setups. Remove the `--coverage` option in all package files

2023-03-07 19:36 UTC, mahula commented on backend/jest.config.js
> -  collectCoverage: true,
Why exactly?
We did not have it in several cases.
As far as I understood this parameter, seems to get overwritten, when we set `collectCoverageFrom`, which sets Jest to collect coverage data from the given glob patterns.

2023-03-07 19:44 UTC, mahula commented
>Remove the `--coverage` option in all package files

Done in https://github.com/gradido/gradido/pull/2790/commits/c2de11e399aaae66824c26c9b6cee16e1a6387b8

2023-03-14 11:35 UTC, ulfgebhardt approved these changes

2023-03-14 12:19 UTC, merged