refactor(database): cleanup database
gradido/gradido pull request #2808
Opened 2023-03-09 23:21 UTC by ulfgebhardt

## 🍰 Pullrequest

Cleanup database, reduce dependencies

### Issues

- None

### Todo

- [X] None

2023-03-14 10:38 UTC, Mogge reviewed
What about line 10 in `backend/src/server/createServer.ts` ?

2023-03-14 10:52 UTC, Mogge reviewed
What about the federation unit tests?

2023-03-21 12:20 UTC, clauspeterhuebner commented
I do not understand the motivation behind this cleanup nor can i follow the changes. Is it possible to give an introduction or at least a more detailed description in the PR?

2023-03-29 09:33 UTC, ulfgebhardt commented
> What about line 10 in `backend/src/server/createServer.ts` ?

You are talking about `import connection from '@/typeorm/connection'`?

This is part of the backend. The local(backend) connection is created with the local config values.

The typeorm include `import { Connection } from '@dbTools/typeorm'` cannot be removed - i tested this - the connection is bound to the path of the typeorm, therefore we need to use the same typeorm so the models (database) and the connection (backend) stem from the same typeorm source.

2023-03-29 09:44 UTC, ulfgebhardt commented
> What about the federation unit tests?

They run, they have no dependencies on the stuff I changed

2023-03-29 09:59 UTC, ulfgebhardt commented
> I do not understand the motivation behind this cleanup nor can i follow the changes. Is it possible to give an introduction or at least a more detailed description in the PR?

We figured out that the config values from backend are used for the database when including the database in the corresponding other project. This is confusing and considered `wrong`. Therefore I wanted to parameterized those parameters and figured out that we don't need all this stuff. E.g. we removed seeding form the database since we noticed we need the business logic.

2023-03-29 21:17 UTC, clauspeterhuebner reviewed
Even with your comments about the motivation of this PR i'am not able to evaluate the changes, because these are too much deep technology dependencies for me. Sorry, please wait for an approvement from @Mogge...

2023-04-03 05:59 UTC, Elweyn requested changes
I tested: 
- ``yarn dev_down``=> Works
- ``yarn dev_down``=> Works
- ``yarn reset``=> Works
- ``yarn dev_reset``=> Error:
```
hannesheine@Hanness-MacBook-Pro:~/workspace/gradido/database (cleanup-database$=) % yarn dev_reset
yarn run v1.22.19
$ cross-env TZ=UTC ts-node src/index.ts reset
Error: Script version and filename mismatch! version: 63 -> file system: 0063-event_link_fields.ts | database: 0063-event_link_fields.js
    at Migration.<anonymous> (/Users/hannesheine/workspace/gradido/database/node_modules/ts-mysql-migrate/src/migrations.ts:230:17)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/hannesheine/workspace/gradido/database/node_modules/ts-mysql-migrate/dist/migrations.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
error Command failed with exit code 1.
```

2023-04-03 06:04 UTC, Elweyn approved these changes

2023-04-03 10:52 UTC, ulfgebhardt commented on database/src/prepare.ts
> +const createDatabase = async (): Promise<void> => {
fixed

2023-04-03 10:53 UTC, ulfgebhardt commented on database/src/prepare.ts
> +export { createDatabase }
fixed

2023-04-03 10:54 UTC, ulfgebhardt commented
> Member

The error occurred since you mixed dev and production datasets. Your database must be either migration.ts or migration.js. That always has been and is a limitation of our migration library.

2023-04-03 11:48 UTC, Elweyn approved these changes

2023-04-03 19:20 UTC, merged