feat(frontend): add link to download QR-Code
gradido/gradido pull request #2889
Opened 2023-03-24 11:24 UTC by Elweyn

## 🍰 Pullrequest

### Issues

- fixes #2825

### Todo

- [X] Add link to download QR-Code

2023-03-30 11:56 UTC, ulfgebhardt requested changes
![image](https://user-images.githubusercontent.com/1238238/228828398-c2687d1b-ab1d-4c42-8bb8-b00eccdc58ed.png)

layouting is suboptimal

Suggestion: Consider to rename `Herunterladen` in `Bild herunterladen`, `Bild speichern`, `QR-Code als Bild speichern`

2023-03-31 08:45 UTC, mahula requested changes

2023-03-31 08:45 UTC, mahula commented on frontend/src/components/QrCode/FigureQrCode.vue
> +  },
What about testing this method?

![qr_tests](https://user-images.githubusercontent.com/3883288/229071753-50d3c1b5-6722-4952-a93a-ddb814e4cfe4.jpg)

2023-04-01 07:42 UTC, mahula commented on frontend/src/components/QrCode/FigureQrCode.vue
> +  },
Resolved by last two commits.

2023-04-01 07:43 UTC, mahula approved these changes
Good solution.
I approve.
Please ping Bernd again to comment on the link naming.

2023-04-01 08:15 UTC, merged