feat(admin): visualize the federation
gradido/gradido pull request #2901
Opened 2023-03-29 10:28 UTC by ogerly

## 🍰 Pullrequest
visualise the federation

- sorted by publicKeys
        oreign: 'ASC',
        createdAt: 'DESC',
        lastAnnouncedAt: 'DESC',

- Displayed 
       verified
      url
      publicKey (0, 26)
      lastAnnouncedAt
      createdAt

The table can be reloaded by hand
 
### Issues
- fixes #2595 

![image](https://user-images.githubusercontent.com/1324583/228504592-ee520364-7fe3-4095-966d-e6e5ed498562.png)

https://user-images.githubusercontent.com/1324583/228506019-4f5b0eb4-c098-49ef-9c97-37e0cbd17b66.mp4

2023-04-05 13:59 UTC, Mogge requested changes

2023-04-05 13:59 UTC, Mogge commented on admin/src/components/Fedaration/FederationVisualizeItem.vue
> +          locale: this.fnsLocale,
```suggestion
          locale: locales[this.locale],
```

2023-04-05 13:59 UTC, Mogge commented on admin/src/components/Fedaration/FederationVisualizeItem.vue
> +      formatDistanceToNow,
What is this for?

2023-04-07 11:26 UTC, mahula commented on admin/src/pages/FederationVisualize.vue
> +      oldPublicKey: '',
What is `oldPublickey` for (it also occures once in FederationVisualizeItem.vue)?

2023-04-07 14:26 UTC, mahula commented on admin/src/components/Fedaration/FederationVisualizeItem.vue
> +    fnsLocale() {
Fixed with 206dcda7750ad1aebce63e44b746610c68224fed.

2023-04-07 14:27 UTC, mahula commented on admin/src/components/Fedaration/FederationVisualizeItem.vue
> +
Fixed with 206dcda7750ad1aebce63e44b746610c68224fed.

2023-04-07 14:27 UTC, mahula commented on admin/src/components/Fedaration/FederationVisualizeItem.vue
> +          locale: this.fnsLocale,
Fixed with 206dcda7750ad1aebce63e44b746610c68224fed.

2023-04-07 14:27 UTC, mahula commented on admin/src/components/Fedaration/FederationVisualizeItem.vue
> +          locale: this.fnsLocale,
Fixed with 206dcda7750ad1aebce63e44b746610c68224fed.

2023-04-07 14:57 UTC, mahula commented on admin/src/pages/FederationVisualize.vue
> +      animation: '',
Done in adcff96e293e87208d1e0fc017ab61c53af07ad9.

2023-04-11 09:29 UTC, Elweyn commented on admin/src/pages/FederationVisualize.spec.js
> +        url: 'http://localhost/api/api/1_1',
```suggestion
        url: 'http://localhost/api/1_1',
```

2023-04-11 09:39 UTC, Elweyn approved these changes

2023-04-11 09:52 UTC, Elweyn approved these changes

2023-04-11 10:04 UTC, merged