feat(frontend): calculator on overview page
gradido/gradido pull request #2954
Opened 2023-04-21 18:05 UTC by Mogge

## 🍰 Pullrequest

![image](https://user-images.githubusercontent.com/15882241/233704899-eceb3ce1-aa39-4d10-866c-3b55469b7721.png)

### Issues

- None

### Todo

- [X] None

2023-04-21 19:04 UTC, BerndHueckstaedt commented
Für "Berechnen" bitte den schicken Button in unserem Design verwenden und auf der rechten Seite anordnen:

<img width="631" alt="image" src="https://user-images.githubusercontent.com/1311557/233714863-b67360db-3b9a-4284-b538-9ab5206981ec.png">

2023-04-24 15:49 UTC, Elweyn requested changes

2023-04-24 15:49 UTC, Elweyn commented on frontend/src/components/Overview/CommunityNews.vue
> +      <h1>Gradido zu DankBar Umrechner</h1>
Please translate!

2023-04-24 15:49 UTC, Elweyn commented on frontend/src/components/Overview/CommunityNews.vue
> +        <span id="tag">{{ tag }}</span>
What is the id used for?

2023-04-24 15:49 UTC, Elweyn commented on frontend/src/components/Overview/CommunityNews.vue
> +        Tag des Jahres:
Please translate!

2023-04-24 15:49 UTC, Elweyn commented on frontend/src/components/Overview/CommunityNews.vue
> +        Faktor:
Please translate!

2023-04-24 15:49 UTC, Elweyn commented on frontend/src/components/Overview/CommunityNews.vue
> +        <span id="faktor">{{ faktor }}</span>
What is the id used for?

2023-04-24 15:49 UTC, Elweyn commented on frontend/src/components/Overview/CommunityNews.vue
> +        <label for="gradido">Gradido:</label>
What is the flag 'for'?

2023-04-24 15:49 UTC, Elweyn commented on frontend/src/components/Overview/CommunityNews.vue
> +        <label for="gradido">Gradido:</label>
And please translate!

2023-04-24 15:49 UTC, Elweyn commented on frontend/src/components/Overview/CommunityNews.vue
> +        <input type="number" id="gradido" name="gradido" v-model="gradido" @input="inputGradido" />
Please use bootstrap!

2023-04-24 15:49 UTC, Elweyn commented on frontend/src/components/Overview/CommunityNews.vue
> +        <input type="number" id="dankbar" name="dankbar" v-model="dankbar" @input="inputDankbar" />
Please use bootstrap!

2023-04-24 15:49 UTC, Elweyn commented on frontend/src/components/Overview/CommunityNews.vue
> +        <br />
Please use CSS with bootstrap

2023-04-24 15:49 UTC, Elweyn commented on frontend/src/components/Overview/CommunityNews.vue
> +        <label for="dankbar">DankBar:</label>
Please translate!

2023-04-24 15:49 UTC, Elweyn commented on frontend/src/components/Overview/CommunityNews.vue
> +      }
Can be written with a cleaner way make the formular interactiv if no value filed then error else give result

2023-04-24 15:49 UTC, Elweyn commented on frontend/src/components/Overview/CommunityNews.vue
> +const start = new Date(jetzt.getFullYear(), 0, 0)
Is loaded one time, so if there is a lot of time until the click on the calculate button this could be wrong!

2023-05-08 12:11 UTC, closed without merging