feat(frontend): new style for settings page, remove unused components
gradido/gradido pull request #3040
Opened 2023-06-08 06:55 UTC by ogerly

## 🍰 Pullrequest
new style for settings page, remove unused components
- dark style modus in settings

### Issues
- fixes #2519 

![Bildschirmfoto vom 2023-06-07 16-36-25](https://github.com/gradido/gradido/assets/1324583/14b1c626-1d28-4c1b-943a-ffe69e26e075)

2023-06-13 05:32 UTC, ogerly commented
![image](https://github.com/gradido/gradido/assets/1324583/feb351ae-37ff-4963-a067-23e69737be1b)

2023-06-13 09:56 UTC, mahula requested changes

2023-06-13 09:56 UTC, mahula commented on frontend/src/components/UserSettings/UserPassword.vue
>      },
The enabling behavior of the submit button does not work as expected:
Expected: after the new password has been enteredand been validated, the button should be enabled.

Current behavior:
When entering the new password the first time, the button gets enabled.
When entering the new password the second time,the button gets disabled.

2023-06-15 13:36 UTC, Elweyn requested changes
Some small changes on the unit the rest seem great!

2023-06-15 13:36 UTC, Elweyn commented on frontend/src/components/Inputs/InputUsername.spec.js
> +        wrapper.vm.currentValue = 'petra swastiska'
Should be done on the input field and not mock it.
Something like this:
```suggestion
        await wrapper.find('div.input-username.input[type="text"]').setValue('petra swastiska')
```

2023-06-15 13:36 UTC, Elweyn commented on frontend/src/components/UserSettings/UserName.spec.js
> +        wrapper.vm.username = 'petra'
```suggestion
        wrapper.findComponent({ name: 'InputUsername' }).setValue('petra')
```

2023-06-15 13:36 UTC, Elweyn commented on frontend/src/pages/Settings.spec.js
> +          wrapper.vm.darkMode = false
please use wrapper.find and click

2023-06-15 13:36 UTC, Elweyn commented on frontend/src/pages/Settings.spec.js
> +        wrapper.find('[data-test="lastname"]')
please use this line 72 and 73

2023-06-28 06:47 UTC, ogerly commented on frontend/src/pages/Settings.spec.js
> +        wrapper.find('[data-test="lastname"]')
done

2023-06-28 07:33 UTC, ogerly commented on frontend/src/pages/Settings.spec.js
> +          wrapper.vm.darkMode = false
done

2023-06-30 16:06 UTC, Elweyn approved these changes

2023-06-30 16:27 UTC, merged