feat(frontend): add humhub switch and name format
gradido/gradido pull request #3309
Opened 2024-04-12 17:47 UTC by einhornimmond

## 🍰 Pullrequest

- add env option for enable humhub
- add switch for user to enable export account to humhub
- add publish name format for humhub based on gms publish name format
- refactor and reuse gms code for this

2024-04-15 19:42 UTC, clauspeterhuebner requested changes
Die gemeinsame aber geänderte Liste der PublishName-Types wird von der GMS-Logik so nicht korrekt verarbeitet werden können

2024-04-15 19:42 UTC, clauspeterhuebner commented on frontend/src/components/UserSettings/UserNamingFormat.spec.js
> +      'settings.publish-name.full',
Wie in der EnumKlasse schon angemerkt, sind die GMS-PublishNames-Types wohl unterschiedlich zu den HumHub-Types.
Es fehlt die Variante "optional Alias oder Initials" und die Varianten "Last" und "Last-Initial" gibt es bei GMS nicht.

2024-04-15 19:42 UTC, clauspeterhuebner commented on frontend/src/locales/de.json
> +    },
Wie schon oben erwähnt passen die GMS-NameTypes und die HumHub-Types nicht zusammen.

2024-04-15 19:42 UTC, clauspeterhuebner commented on frontend/src/locales/en.json
> +    },
siehe Bemerkung in de.json

2024-04-16 12:53 UTC, einhornimmond commented
> Die gemeinsame aber geänderte Liste der PublishName-Types wird von der GMS-Logik so nicht korrekt verarbeitet werden können

Stimmt, deshalb ist es ja auch ein eigenständiges, neues enum, ohne gms im Namen. 
Es behandelt nur die verschiedenen Arten wie Vor- und Nachname in einem externen Dienst wie HumHub veröffentlicht werden. Der Benutzername wird davon unabhängig behandelt, da der in humhub unique sein muss.

2024-04-16 13:01 UTC, einhornimmond commented on backend/src/util/communityUser.ts
> +  humhubAllowed: false,
communityUser wird als Template verwendet wenn man mal einen User simulieren möchte.
Es wird verwendet um einen Fake User zurückzugeben falls die E-Mail mit der man ein neues Konto anlegen will bereits existiert und für den linked User in einer creation in der Transaktionsliste. 
Ich würde das daher lieber beides auf false belassen.

2024-04-16 13:02 UTC, einhornimmond commented on database/entity/0084-introduce_humhub_registration/User.ts
> +  humhubAllowed: boolean
siehe oben

2024-04-16 13:02 UTC, einhornimmond commented on database/migrations/0084-introduce_humhub_registration.ts
> +    'ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `humhub_allowed` tinyint(1) NOT NULL DEFAULT 0 AFTER `gms_registered_at`;',
siehe oben

2024-04-16 13:04 UTC, einhornimmond commented on frontend/src/locales/de.json
> +    },
Gut erkannt, daher ist es extra.

2024-04-16 19:05 UTC, clauspeterhuebner commented on backend/src/graphql/resolver/UserResolver.test.ts
> +              humhubAllowed: false,
Ja da hast du recht und wir haben das heute ja auch so beschlossen, dass beide per default auf false gesetzt werden sollen.

2024-04-16 19:06 UTC, clauspeterhuebner commented on database/entity/0084-introduce_humhub_registration/User.ts
> +  humhubAllowed: boolean
richtig

2024-04-16 19:07 UTC, clauspeterhuebner commented on database/migrations/0084-introduce_humhub_registration.ts
> +    'ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `humhub_allowed` tinyint(1) NOT NULL DEFAULT 0 AFTER `gms_registered_at`;',
korrekt

2024-04-16 19:09 UTC, clauspeterhuebner commented on frontend/src/components/UserSettings/UserNamingFormat.spec.js
> +      'settings.publish-name.full',
Ach so, dann habe ich das bisher falsch verstanden. Sorry. Ich dachte du hast die Enum-Klasse von den GMSNameTypes verwendet.
Nach der heutigen Entscheidung sollten wir schauen, dass wir für GMS und für HumHub die gleichen Varianten verwenden.

2024-04-16 19:10 UTC, clauspeterhuebner commented on frontend/src/locales/de.json
> +    },
korrekt

2024-04-16 19:24 UTC, clauspeterhuebner approved these changes
vorbehaltlich dem neu beschlossenen GMS- und HumHub-Publishing.
Ich erstelle dazu das/die entsprechende(n) Ticket(s)

2024-04-16 19:24 UTC, clauspeterhuebner commented on backend/src/graphql/enum/PublishNameType.ts
> +  PUBLISH_NAME_FULL = 6,
siehe neu beschlossenes GMS- und HumHub-Publishing

2024-04-19 09:26 UTC, merged