fix(backend): fix test which will only fail at 31. of month, or 30.05
gradido/gradido pull request #3320
Opened 2024-05-31 16:56 UTC by einhornimmond

## 🍰 Pullrequest
This pull request addresses an issue with date calculations in our codebase, specifically when subtracting months from dates that fall at the end of a month, such as 31st May or 31st July. The previous method using Date.prototype.setMonth resulted in erroneous outcomes. For instance, subtracting three months from 31st May yielded March instead of February. This new function ensures that the correct month is calculated by setting the day to the 1st before performing the month subtraction.

### Todo

- [x] Implemented the getFirstDayOfPreviousNMonth function to accurately calculate dates.
- [x] Updated existing tests to use the new function, thus preventing failures on dates such as 31st May, 31st July, and 30th May.
- [x] updating getCreationDates using the new function, make it more readable

2024-06-03 23:52 UTC, clauspeterhuebner requested changes
Die Lösung trifft nicht ganz alle möglichen EdgeCases eines Datums
Siehe Kommentar und diese Library: https://github.com/datejs/Datejs

2024-06-03 23:52 UTC, clauspeterhuebner commented on backend/src/util/utilities.ts
> +  new Date(startDate.getFullYear(), startDate.getMonth() - monthsAgo, 1)
Was passiert wenn startDate = 14.02.2024 und monthAgo=3 ?
Dann sollte das Ergebnis 14.12.2023 sein.
Behandelt diese Lösung die vielen EdgeCases eines Datums wie Jahreswechsel oder Wechsel auf Monate mit weniger Tagen?

Hast du dir diese Library https://github.com/datejs/Datejs schon einmal angeschaut?

2024-06-04 11:33 UTC, einhornimmond commented on backend/src/util/utilities.ts
> +  new Date(startDate.getFullYear(), startDate.getMonth() - monthsAgo, 1)
Hast du meinen (genaugenommen hat ChatGPT den formuliert) Kommentar zur Funktion gelesen? Hast du verstanden wie meine Funktion funktioniert?

Für startDate = 14.02.2024 und monthAgo = 3 ist das Ergebnis 01.11.2023
- Start Datum Februar
- -1 Monat :  01. Januar 2024
- -2 Monate: 01. Dezember 2023
- -3 Monate: 01. November 2023

Da wir eigentlich nur Monat und Jahr für den Code brauchen, können wir hier den Tag einfach auf 1 setzen und ersparen uns damit weitere Schwierigkeiten und Besonderheiten.
Ich habe meinen PR noch um Tests ergänzt, insbesondere für bestimmte Grenzfälle.

2024-06-04 15:32 UTC, clauspeterhuebner commented on backend/src/util/utilities.ts
> +  new Date(startDate.getFullYear(), startDate.getMonth() - monthsAgo, 1)
Prima, das passt für mich. Über die Library haben wir ja gesprochen...

2024-06-04 16:48 UTC, clauspeterhuebner approved these changes

2024-06-05 06:22 UTC, merged