437 bug mobile transaction list is not easy to read
gradido/gradido pull request #462
Opened 2021-05-19 12:34 UTC by ogerly

## 🍰 Pullrequest
Transactions list clearer + date visible

### Issues
- fixes #437 
 

![FireShot Capture 524 - Gradido Account - localhost](https://user-images.githubusercontent.com/1324583/118813364-56347c80-b8af-11eb-89a7-c63c92c7df09.png)
![FireShot Capture 521 - Gradido Account - localhost](https://user-images.githubusercontent.com/1324583/118813374-5896d680-b8af-11eb-9d85-bd10d0e597c2.png)

2021-05-19 13:54 UTC, einhornimmond commented
Looks better now, but I'm not sure if I like the + or - symbol after the numbers.

2021-05-19 13:54 UTC, einhornimmond approved these changes

2021-05-19 15:09 UTC, Mogge requested changes
Ich versuche den anderen PR von mir hier raus zubekommen. Bitte kümmere dich um eine saubere Funktionalität der Icons und Classes

2021-05-19 15:09 UTC, Mogge commented on frontend/src/views/Pages/AccountOverview/GddTransactionList.vue
> +          </div>
Das geht besser. Sowas wie
```
:icon="getIcon(item)"
:class="getClass(item)"
```

```
const iconsByType = {
  send: 'arrow-left-cricle',
  ...
}
```

```
getIcon(item) {
  const icon = iconsByType[item.type]
  if (icon) return icon
  new Error('no item to given type') 
}
```

2021-05-19 15:09 UTC, Mogge commented on frontend/src/views/Pages/ResetPassword.vue
> +        })
Das gehört hier nicht hin

2021-05-19 15:09 UTC, Mogge commented on frontend/src/views/Pages/thx.vue
> +}
Weg damit

2021-05-20 04:21 UTC, ogerly commented on frontend/src/locales/de.json
> +      "email": "Wir haben dir eine eMail gesendet.",
habe ich geändert

2021-05-20 04:22 UTC, ogerly commented on frontend/src/locales/en.json
> +      "reset": "Your password has been changed",
das habe ich geändert

2021-05-20 04:32 UTC, ogerly commented on frontend/src/routes/routes.js
> +    },
`
 } else {        
    next()     
 }`

entfernt

2021-05-20 07:52 UTC, ogerly reviewed
erledigt

2021-05-20 11:30 UTC, Mogge requested changes

2021-05-20 11:30 UTC, Mogge commented on frontend/src/views/Pages/AccountOverview/GddTransactionList.vue
> +      <div v-if="transactions.length !== 0" class="mt-4 text-center">
![image](https://user-images.githubusercontent.com/15882241/118971187-66139580-b96f-11eb-9413-08a3c48472c8.png)

2021-05-20 14:03 UTC, einhornimmond approved these changes

2021-05-21 06:52 UTC, Mogge approved these changes

2021-05-21 06:53 UTC, merged