[WIP] Feature: Cange Username
gradido/gradido pull request #490
Opened 2021-06-08 15:02 UTC by ogerly

## 🍰 Pullrequest

### Issues

- None

### Todo

- [X] None

2021-06-09 08:23 UTC, ogerly commented
![FireShot Capture 659 - Gradido Account - localhost](https://user-images.githubusercontent.com/1324583/121319660-b9dd2300-c90c-11eb-97e2-3ffe31e4d78d.png)
![FireShot Capture 660 - Gradido Account - localhost](https://user-images.githubusercontent.com/1324583/121319668-bba6e680-c90c-11eb-8518-cc28fba13676.png)
![FireShot Capture 661 - Gradido Account - localhost](https://user-images.githubusercontent.com/1324583/121319676-bcd81380-c90c-11eb-9b43-d6c8a02dbaa9.png)

2021-06-09 09:14 UTC, ulfgebhardt requested changes

2021-06-09 09:14 UTC, ulfgebhardt commented on frontend/src/views/Pages/UserProfile/UserCard_FormUsername.vue
> +        alert('Dein Username wurde geändert.')
```suggestion
        alert('Dein Username wurde geändert.')
```

Can we remove this  and show the user in a different form?

2021-06-14 11:18 UTC, ulfgebhardt approved these changes

2021-06-14 13:59 UTC, merged