[WIP] - Css color input error
gradido/gradido pull request #646
Opened 2021-07-16 13:48 UTC by ogerly

## 🍰 Pullrequest
css color change

### Issues
<!-- Which Issues does this fix, which are related?
- fixes #604

2021-07-16 13:51 UTC, ollivah approved these changes

2021-07-17 15:47 UTC, Mogge requested changes
Ich habe im Register.vue noch nicht die neuen Komponenten eingebaut, da auf production keine Registrierung möglich ist. Wenn du jetzt aber schon dran bist, dann bau doch bitte die Komponenten ein.

2021-07-17 15:47 UTC, Mogge commented on frontend/src/views/Pages/Register.vue
> +                          <b-button
Bitte die InputPasswordConfirmation Komponente benutzen.

2021-07-18 07:46 UTC, ogerly commented on frontend/src/views/Pages/Register.vue
> +                          <b-button
ok .. mache ich

2021-07-19 08:50 UTC, Mogge requested changes

2021-07-19 08:50 UTC, Mogge commented on frontend/src/components/Inputs/InputEmail.vue
> +      </b-form-invalid-feedback>
Super Lösung! Da wäre ich nie drauf gekommen.

2021-07-19 08:50 UTC, Mogge commented on frontend/src/components/Inputs/InputEmail.vue
> +        class="email-form-input"
Brauchs das hier noch, und das CSS am Ende?

2021-07-20 12:36 UTC, Elweyn commented
This issue should be pushed to the next deployment. @ogerly @Mogge

2021-08-05 13:50 UTC, Mogge approved these changes

2021-08-05 13:52 UTC, merged