mobile friendly, add text, change text
gradido/gradido pull request #683
Opened 2021-07-28 11:40 UTC by ogerly

## 🍰 Pullrequest
mobile friendly view of the userprofile 

### Issues
<!-- Which Issues does this fix, which are related?
- fixes #522

https://user-images.githubusercontent.com/1324583/127316353-bb221a16-ade1-4b13-87b6-157d71a76ac6.mp4

2021-07-30 07:46 UTC, ulfgebhardt approved these changes

2021-07-30 07:50 UTC, ulfgebhardt commented
![image](https://user-images.githubusercontent.com/1238238/127619931-b181082f-51d0-48e9-b91a-b0b757ce9e61.png)

2021-08-04 15:00 UTC, Mogge requested changes
Du hast den Test kaput gemacht, der schaut, dass die Felder zurück gesetzt werden, wenn auf den cancel Knopf getippt wird. Statt das Verhalten der Komponente zu korrigieren, hast du den Test geändert, aber dadurch 25% Line-Coverage  in dieser Datei verloren, da die Komponente die Funktion nicht mehr aufgerufen hat. Bitte nicht so ohne weiteres die Tests ändern, wenn sich an der funktionalität nichts geändert hat. @ulfgebhardt du hättest das nicht approven dürfen.

2021-08-04 15:00 UTC, Mogge commented on frontend/src/views/Pages/UserProfile/UserCard_FormUserData.vue
> +            <a @click="showUserData ? (showUserData = !showUserData) : cancelEdit()">
Das musste ich ändern damit der test wieder läuft wie er war.

2021-08-04 15:00 UTC, Mogge commented on frontend/src/views/Pages/UserProfile/UserCard_FormUserPasswort.vue
> +            <a v-if="!editPassword" href="#change_pwd" @click="editPassword = !editPassword">
Wozu braucht es das href hier? Die Rute sieht nicht schön aus. Vielleicht den gleichen Trick verwenden wie im ChangeUserData (statt zwei a-Elementen)?

2021-08-04 15:06 UTC, ulfgebhardt commented
> Du hast den Test kaput gemacht, der schaut, dass die Felder zurück gesetzt werden, wenn auf den cancel Knopf getippt wird. Statt das Verhalten der Komponente zu korrigieren, hast du den Test geändert, aber dadurch 25% Line-Coverage in dieser Datei verloren, da die Komponente die Funktion nicht mehr aufgerufen hat. Bitte nicht so ohne weiteres die Tests ändern, wenn sich an der funktionalität nichts geändert hat. @ulfgebhardt du hättest das nicht approven dürfen.

Sorry das hab ich nicht gesehen 💔

2021-08-05 14:01 UTC, Mogge approved these changes

2021-08-05 14:08 UTC, merged