585 coin animation on and off switchable
gradido/gradido pull request #813
Opened 2021-09-16 06:39 UTC by ogerly

## 🍰 Pullrequest
coin animation on and off switchable in user settings 

### Issues
- fixes #585
 
 todo: @Elweyn @Mogge   
 es müssen im store ein neuer punkt eingefügt werden "coinanimation"
 - dieser sollte wohl auch in der DB für den user exestieren

2021-09-21 07:03 UTC, Elweyn commented
@ulfgebhardt, @clauspeterhuebner, 
@ogerly and me are speaking about this issue. And their would be some todos on the backend.
- [ ] Database User stores the coinanimation flag
- [ ] Get User in Apollo and LoginServer gives back the coinanimation flag of a User
- [ ] Update User in LoginServer can update the coinanimation flag of a User

2021-09-24 12:54 UTC, ogerly commented
classe anpassen from style

2021-09-29 10:55 UTC, Elweyn commented
@einhornimmond Assigned you to this task/PR since we need to store the flag to the database in the user table

2021-10-01 18:03 UTC, einhornimmond commented
So, coinanimation will be stored in new settings table (key-value approach)
It will be saved from frontend and load by login into frontend

Attention: to get database migration to work, database_build volume must be deleted first and database must be builded. 

By testing it coinanimation don't seem to stop after disabling it and the locale for it is also missing.

2021-10-02 15:04 UTC, ulfgebhardt requested changes

2021-10-02 15:04 UTC, ulfgebhardt commented on backend/src/util/validate.ts
> +}
pretty sure this can be simplified

2021-10-02 15:04 UTC, ulfgebhardt commented on login_server/src/cpp/JSONInterface/JsonUpdateUserInfos.cpp
> +
docu missing

2021-10-02 15:16 UTC, ulfgebhardt approved these changes

2021-10-02 18:06 UTC, merged

2021-10-02 20:19 UTC, ogerly commented
sehr geil

2021-10-03 15:06 UTC, Mogge reviewed
I really do not understand the rush of this PR. I question the solution in creating a hash table for the user settings. Why not simply add a column to the `user_state` table with a boolean value for the coin animation? The hack to convert a string into a boolean is so ugly ...

2021-10-03 15:06 UTC, Mogge commented on backend/src/graphql/resolvers/UserResolver.ts
> +import { Setting } from '../../graphql/enum/Setting'
I suggest the name Settings

2021-10-03 15:06 UTC, Mogge commented on backend/src/graphql/enum/Setting.ts
> +enum Setting {
Settings as well the filename