refactor: [WIP] Queries to Mutations
gradido/gradido pull request #863
Opened 2021-09-20 09:31 UTC by Mogge

## 🍰 Pullrequest
Makes the queries that alter data in the DB to mutations

### Issues
- fixes #742

2021-09-20 18:11 UTC, ulfgebhardt requested changes

2021-09-20 18:11 UTC, ulfgebhardt commented on frontend/src/views/Pages/Register.spec.js
> +const resgisterUserMutationMock = jest.fn()
```suggestion
const registerUserMutationMock = jest.fn()
```

2021-09-20 18:11 UTC, ulfgebhardt commented on frontend/src/views/Pages/Register.vue
> +import { resgisterUser } from '../../graphql/mutations'
```suggestion
import { registerUser } from '../../graphql/mutations'
```

2021-09-20 18:11 UTC, ulfgebhardt commented on frontend/src/graphql/mutations.js
> +export const resgisterUser = gql`
```suggestion
export const registerUser = gql`
```

2021-09-21 10:06 UTC, Elweyn approved these changes
Seems good for me except the name change (resgister => register) that @ulfgebhardt asked for.

2021-09-23 09:57 UTC, Mogge commented
Thx for the catch @ulfgebhardt

2021-09-23 11:32 UTC, ulfgebhardt commented
> Thx for the catch @ulfgebhardt

I think that is not a problem introduced in this PR, but I mean its fair to fix it right? ;)

2021-09-23 11:35 UTC, ulfgebhardt approved these changes

2021-09-23 18:46 UTC, merged