Apollo list transactions
gradido/gradido pull request #893
Opened 2021-09-24 09:05 UTC by einhornimmond

## 🍰 Pullrequest
Implement listTransactions call from Community Server into Apollo

### Issues
- fixes #822 

### Todo 
- [x] load gdt sum and gdd balance with decay
- [x] add UserTransaction Model for table state_user_transactions
- [x] implement paging 
- [ ] add Transactions Model for table transactions
- [ ] add TransactionSendCoin Model for table transaction_send_coins
- [ ] add TransactionCreation Model for table transaction_creations
- [ ] implement calculating decay transactions and add them

2021-09-28 17:11 UTC, ulfgebhardt commented
This looks very good. What is missing?

2021-09-29 08:33 UTC, einhornimmond commented
Decay don't work properly

2021-09-30 16:49 UTC, ulfgebhardt requested changes

2021-09-30 16:49 UTC, ulfgebhardt commented on backend/src/graphql/resolvers/listTransactions.ts
> +    } else if (userTransaction.transactionTypeId === 2) {
```suggestion
    } else if (userTransaction.transactionTypeId === TRANSACTION_TYPES.TYPE_2) {

2021-09-30 16:49 UTC, ulfgebhardt commented on backend/src/graphql/resolvers/listTransactions.ts
> +        finalTransaction.type = 'send'
```suggestion
        finalTransaction.type = TRANSACTION_TYPE_NAMES.SEND
```

2021-09-30 16:49 UTC, ulfgebhardt commented on backend/src/graphql/resolvers/listTransactions.ts
> +        finalTransaction.type = 'receive'
enum pls

2021-09-30 16:49 UTC, ulfgebhardt commented on backend/src/graphql/resolvers/listTransactions.ts
> +  order: 'ASC' | 'DESC',
enum pls compatible with the graphql

2021-09-30 16:49 UTC, ulfgebhardt commented on backend/src/graphql/resolvers/listTransactions.ts
> +  if (offset && order === 'ASC') {
enum

2021-09-30 16:49 UTC, ulfgebhardt commented on backend/src/graphql/resolvers/listTransactions.ts
> +    if (order === 'DESC') {
enum

2021-09-30 16:49 UTC, ulfgebhardt commented on backend/src/graphql/resolvers/listTransactions.ts
> +    if (order === 'DESC') {
enum

2021-09-30 16:49 UTC, ulfgebhardt commented on backend/src/typeorm/entity/UserTransaction.ts
> +    order: 'ASC' | 'DESC',
enum

2021-09-30 16:49 UTC, ulfgebhardt commented on backend/src/util/decay.ts
> +  const result = new Decay(undefined)
can we use `new Decay()`instead of explicit `undefined` pls

2021-09-30 16:49 UTC, ulfgebhardt commented on backend/src/util/decay.ts
> +  to: number | Date,
require date only?

2021-09-30 16:49 UTC, ulfgebhardt commented on backend/src/util/decay.ts
> +  if (decayStartBlock === undefined || decayStartBlock.received.getTime() > toMillis) {
```suggestion
  if (!decayStartBlock || decayStartBlock.received.getTime() > toMillis) {
```

2021-09-30 16:58 UTC, ulfgebhardt approved these changes

2021-09-30 17:02 UTC, merged