feat: Test Change Language in User Profile
gradido/gradido pull request #904
Opened 2021-09-27 13:07 UTC by Mogge

## 🍰 Pullrequest
Test the new component to change the language in the user profile

2021-09-28 17:08 UTC, ulfgebhardt requested changes

2021-09-28 17:08 UTC, ulfgebhardt commented on frontend/src/views/Pages/UserProfile/UserCard_Newsletter.spec.js
> +    describe('subscribe with sucess', () => {
```suggestion
    describe('subscribe with success', () => {
```

2021-09-28 17:08 UTC, ulfgebhardt commented on frontend/src/views/Pages/UserProfile/UserCard_Newsletter.spec.js
>      describe('unsubscribe with sucess', () => {
```suggestion
    describe('unsubscribe with success', () => {
```

2021-09-30 12:28 UTC, ogerly approved these changes

2021-10-01 08:14 UTC, ulfgebhardt approved these changes

2021-10-01 10:07 UTC, merged