refactor: Provide pubKey in Resolver Context to Avoid API Calls
gradido/gradido pull request #906
Opened 2021-09-27 17:07 UTC by Mogge

## 🍰 Pullrequest
Encodes the `pubKey` in the JWT to provide the key in the context object of API calls that require authorization.

2021-09-27 17:55 UTC, einhornimmond approved these changes

2021-09-27 18:46 UTC, ulfgebhardt requested changes

2021-09-27 18:46 UTC, ulfgebhardt commented on backend/src/jwt/decode.ts
>    if (!token) return new Error('401 Unauthorized')
```suggestion
  if (!token) throw new Error('401 Unauthorized')
```

2021-09-27 18:46 UTC, ulfgebhardt commented on backend/src/jwt/decode.ts
>  export default (token: string): any => {
```suggestion
export default (token: string): { token, sessionId, pubKey } => {
```

2021-09-27 18:46 UTC, ulfgebhardt commented on backend/src/jwt/decode.ts
>  /* eslint-disable @typescript-eslint/no-explicit-any */
```suggestion
```

2021-10-01 10:48 UTC, ulfgebhardt approved these changes

2021-10-01 10:52 UTC, merged