Clean models
gradido/gradido pull request #911
Opened 2021-09-28 11:39 UTC by ulfgebhardt

## 🍰 Pullrequest

Clean models - use DataMapper instead of Active Record pattern.
I duplicate code here which could be solved by crating a custom Repository. I would recommend to not create a custom repository but change the query from a publicKey find to an EMail find in the future.

### Issues

- None

### Todo

- [X] None

2021-09-28 14:25 UTC, einhornimmond approved these changes
no comment

2021-09-28 18:15 UTC, Mogge approved these changes
Cool!

2021-09-29 11:05 UTC, Elweyn requested changes

2021-09-29 11:05 UTC, Elweyn commented on backend/src/graphql/resolvers/GdtResolver.ts
> +      .getOneOrFail()
Same as BalanceResolver userEntity

2021-10-01 18:47 UTC, ulfgebhardt commented
Closing in favor of #927 and #928

2021-10-01 18:47 UTC, closed without merging